import type { ExecutionMandate } from "../domain/index.js";
import { evaluateMandate, isCanonicalFrozenArray, isCanonicalFrozenObject, validMandate, type EvaluationPolicy, type EvaluationWorkflow, type ExecutionIntent, type LiveAccountState, type LiveMarketState, type StateEnvelope, type RefusalCode } from "../evaluator/index.js";
import { ORDER_OUTCOMES, OrderWriter, type FillEvent, type OrderReceipt } from "../execution/index.js";
import { createMandateRuntime, transition, type MandateRuntime } from "./mandateRuntime.js";
import { MANDATE_STATES, isLegalTransition, type MandateState } from "./mandateState.js";
import type { MandateTransitionEvent } from "./mandateEvents.js";

export type CapabilityMode = "SHADOW" | "LOCAL_REPLAY";
export type WorkflowStatus = "READY" | "TRIGGERED" | "VALIDATING" | "SUBMITTING" | "ACKNOWLEDGED" | "PARTIALLY_FILLED" | "FILLED" | "REFUSED" | "REJECTED" | "FAILED" | "UNKNOWN" | "RECOVERY_BLOCKED" | "CANCELLED";
export type WorkflowMarketState = StateEnvelope<LiveMarketState>;
export type WorkflowAccountState = StateEnvelope<LiveAccountState>;
export interface WorkflowReceipt { readonly kind: "WORKFLOW_RECEIPT"; readonly workflowId: string; readonly mandateId: string; readonly version: number; readonly status: WorkflowStatus; readonly runtime: MandateRuntime; readonly authorityStatus: EvaluationWorkflow["authorityStatus"]; readonly orderOutcome?: OrderReceipt["outcome"]; readonly clientOrderId?: string; readonly refusalCode?: RefusalCode; readonly recoveryStatus?: "RECONCILED"; }
export interface WorkflowRecord extends WorkflowReceipt { readonly mandate: ExecutionMandate; readonly market: WorkflowMarketState; readonly account: WorkflowAccountState; readonly evaluationPolicy: EvaluationPolicy; }
export interface WorkflowPersistence { load(workflowId: string): WorkflowRecord | undefined; save(record: WorkflowRecord, expectedVersion?: number): Promise<void>; compareAndSave(record: WorkflowRecord, expectedVersion: number): Promise<void>; }
export const WORKFLOW_PERSISTENCE_CAS_CAPABILITY = Symbol.for("0-infinity.workflow-persistence.cas");
export interface CASWorkflowPersistence extends WorkflowPersistence { readonly [WORKFLOW_PERSISTENCE_CAS_CAPABILITY]: true; }
export class MemoryWorkflowPersistence implements WorkflowPersistence {
  readonly [WORKFLOW_PERSISTENCE_CAS_CAPABILITY] = true as const;
  private readonly records = new Map<string, WorkflowRecord>();
  load(id: string): WorkflowRecord | undefined { const r = this.records.get(id); return r ? frozen(structuredClone(r)) : undefined; }
  async save(record: WorkflowRecord, expectedVersion?: number): Promise<void> {
    const current = this.records.get(record.workflowId);
    if (expectedVersion === -1 ? current !== undefined : expectedVersion !== undefined && (!current || current.version !== expectedVersion)) throw new Error("WORKFLOW_VERSION_CONFLICT");
    this.records.set(record.workflowId, frozen(structuredClone(record)));
  }
  async compareAndSave(record: WorkflowRecord, expectedVersion: number): Promise<void> { return this.save(record, expectedVersion); }
}
export interface RuntimeSupervisorOptions { readonly mode: CapabilityMode; readonly writer: OrderWriter; readonly persistence: WorkflowPersistence; readonly clock: () => number; }
export interface StartWorkflowInput { readonly workflowId: string; readonly mandate: ExecutionMandate; readonly market: WorkflowMarketState; readonly account: WorkflowAccountState; readonly evaluationPolicy: EvaluationPolicy; readonly authorityStatus: EvaluationWorkflow["authorityStatus"]; }
function frozen<T>(value: T): T { if (value && typeof value === "object" && !Object.isFrozen(value)) { Object.freeze(value); for (const child of Object.values(value as object as Record<string, unknown>)) frozen(child); } return value; }
function deepFrozen(value: unknown, seen = new Set<object>()): boolean { if (!value || typeof value !== "object") return true; if (seen.has(value)) return true; seen.add(value); return Object.isFrozen(value) && Reflect.ownKeys(value).every((k) => { const d = Object.getOwnPropertyDescriptor(value, k); return !!d && "value" in d && deepFrozen(d.value, seen); }); }
function finite(v: unknown): v is number { return typeof v === "number" && Number.isFinite(v); }
function validEnvelope(value: unknown, kind: "market" | "account", now = Number.POSITIVE_INFINITY): boolean {
  const x = value as Record<string, any>; const valueKeys = kind === "market" ? ["venue", "instrument", "symbol", "bidPrice", "askPrice", "markPrice", "expectedMoveBps", "spreadBps", "slippageBps", "feeBps", "fundingCostBps"] : ["accountId", "availableNotional", "currentNotional", "currentLossBps"];
  if (!isCanonicalFrozenObject(value, ["version", "observedAt", "receivedAt", "value"]) || !isCanonicalFrozenObject(x.value, valueKeys)) return false;
  if (typeof x.version !== "bigint" || x.version < 0n || !finite(x.observedAt) || x.observedAt < 0 || x.observedAt > now || !finite(x.receivedAt) || x.receivedAt < x.observedAt || x.receivedAt > now || !deepFrozen(value)) return false;
  const v = x.value as any;
  if (kind === "market") {
    const nums = [v.bidPrice, v.askPrice, v.markPrice, v.expectedMoveBps, v.spreadBps, v.slippageBps, v.feeBps, v.fundingCostBps];
    const midpointSpread = finite(v.bidPrice) && finite(v.askPrice) && v.bidPrice + v.askPrice > 0 ? (v.askPrice - v.bidPrice) / ((v.askPrice + v.bidPrice) / 2) * 10_000 : NaN;
    return v.venue === "BINANCE" && ["SPOT", "USD_M_FUTURES"].includes(v.instrument) && typeof v.symbol === "string" && v.symbol.length > 0 && nums.every((n: unknown) => finite(n) && (n as number) >= 0) && v.bidPrice > 0 && v.askPrice > 0 && v.bidPrice <= v.askPrice && v.markPrice >= v.bidPrice && v.markPrice <= v.askPrice && v.spreadBps === midpointSpread;
  }
  return typeof v.accountId === "string" && v.accountId.length > 0 && [v.availableNotional,v.currentNotional,v.currentLossBps].every((n: unknown) => finite(n) && (n as number) >= 0);
}
function validPolicy(value: unknown): value is EvaluationPolicy { const x = value as any; return isCanonicalFrozenObject(value, ["maxMarketAgeMs", "maxAccountAgeMs", "maxAnchorVersionLag"]) && finite(x.maxMarketAgeMs) && x.maxMarketAgeMs >= 0 && finite(x.maxAccountAgeMs) && x.maxAccountAgeMs >= 0 && typeof x.maxAnchorVersionLag === "bigint" && x.maxAnchorVersionLag >= 0n; }
function transitionOrThrow(runtime: MandateRuntime, event: MandateTransitionEvent, at: number, reason: string): MandateRuntime { const result = transition(runtime, event, { at, reason }); if (!result.ok) throw new Error(result.rejection.message); return result.machine; }
function statusFor(outcome: OrderReceipt["outcome"]): WorkflowStatus { return outcome === "ACKNOWLEDGED" ? "ACKNOWLEDGED" : outcome === "PARTIALLY_FILLED" ? "PARTIALLY_FILLED" : outcome === "FILLED" ? "FILLED" : outcome === "CANCELLED" ? "CANCELLED" : outcome === "UNKNOWN" ? "UNKNOWN" : "FAILED"; }
function eventFor(outcome: OrderReceipt["outcome"]): MandateTransitionEvent | undefined { return outcome === "ACKNOWLEDGED" ? { type: "ACKNOWLEDGE" } : outcome === "PARTIALLY_FILLED" ? { type: "PARTIAL_FILL" } : outcome === "FILLED" ? { type: "FILL" } : outcome === "CANCELLED" ? { type: "CANCEL" } : outcome === "REJECTED" || outcome === "FAILED" ? { type: "FAIL" } : outcome === "UNKNOWN" ? { type: "SUBMIT_UNKNOWN" } : undefined; }
function validRuntime(runtime: unknown, now: number): runtime is MandateRuntime { if (!isCanonicalFrozenObject(runtime, ["state", "expiresAt", "history"]) || !deepFrozen(runtime)) return false; const x = runtime as unknown as MandateRuntime; if (!MANDATE_STATES.includes(x.state) || !finite(x.expiresAt) || x.expiresAt < 0 || !isCanonicalFrozenArray(x.history)) return false; let prior: MandateState = "ARMED", at = -Infinity; for (const h of x.history) { if (!isCanonicalFrozenObject(h, ["fromState", "toState", "at"], ["reason"]) || h.fromState !== prior || !MANDATE_STATES.includes(h.toState) || !finite(h.at) || h.at < 0 || h.at > now || h.at < at || (h.reason !== undefined && typeof h.reason !== "string") || !isLegalTransition(h.fromState, h.toState)) return false; prior = h.toState; at = h.at; } return prior === x.state; }
function validRecord(record: unknown, now: number): record is WorkflowRecord {
  if (!isCanonicalFrozenObject(record, ["kind", "workflowId", "mandateId", "version", "status", "runtime", "authorityStatus", "mandate", "market", "account", "evaluationPolicy"], ["orderOutcome", "clientOrderId", "refusalCode", "recoveryStatus"]) || !deepFrozen(record)) return false;
  const x = record as unknown as WorkflowRecord;
  if (!x.mandate || !x.market || !x.account || !x.evaluationPolicy || x.kind !== "WORKFLOW_RECEIPT" || typeof x.workflowId !== "string" || x.workflowId.length === 0 || x.mandateId !== x.mandate.mandateId || x.workflowId !== x.mandate.workflowId || !Number.isSafeInteger(x.version) || x.version < 0 || !validMandate(x.mandate) || !validEnvelope(x.market, "market", now) || !validEnvelope(x.account, "account", now) || !validPolicy(x.evaluationPolicy) || !["ACTIVE","SUPERSEDED","REVOKED","CONSUMED"].includes(String(x.authorityStatus)) || !validRuntime(x.runtime, now) || x.runtime.expiresAt !== x.mandate.expiresAt || x.status === "RECOVERY_BLOCKED") return false;
  const expectedRuntime: Record<string, string> = { ARMED: "READY", REFUSED: "REFUSED", ACKNOWLEDGED: "ACKNOWLEDGED", PARTIALLY_FILLED: "PARTIALLY_FILLED", FILLED: "FILLED", CANCELLED: "CANCELLED", FAILED: "FAILED", UNKNOWN: "UNKNOWN" };
  if (expectedRuntime[x.runtime.state] !== x.status) return false;
  if (x.orderOutcome !== undefined && !ORDER_OUTCOMES.includes(x.orderOutcome)) return false;
  if (x.clientOrderId !== undefined && (typeof x.clientOrderId !== "string" || !/^mb5-[0-9a-f]{48}$/.test(x.clientOrderId))) return false;
  if (x.orderOutcome !== undefined && x.clientOrderId === undefined) return false;
  if (x.clientOrderId !== undefined && x.orderOutcome === undefined) return false;
  if (x.clientOrderId !== undefined && x.clientOrderId !== OrderWriter.clientOrderId({ mandateId: x.mandateId, workflowId: x.workflowId } as any, 0)) return false;
  if (x.refusalCode !== undefined && (!(["INVALID_BINDING", "AUTHORITY_STATUS", "RUNTIME_NOT_EXECUTABLE", "MANDATE_EXPIRED", "MARKET_STATE_STALE", "ACCOUNT_STATE_STALE", "STATE_VERSION_STALE", "STATE_BINDING", "ENTRY_TRIGGER_NOT_MET", "ENTRY_PRICE_OUT_OF_BOUNDS", "COST_CEILING", "EXECUTABLE_EDGE_TOO_LOW", "RISK_LIMIT", "EXPOSURE_LIMIT"] as readonly string[]).includes(x.refusalCode) || x.status !== "REFUSED")) return false;
  if (x.status === "REFUSED" && x.refusalCode === undefined) return false;
  if (x.recoveryStatus !== undefined && (x.recoveryStatus !== "RECONCILED" || x.runtime.state !== "UNKNOWN" || x.orderOutcome === undefined || x.orderOutcome === "UNKNOWN")) return false;
  if (x.runtime.state === "UNKNOWN" && (x.status !== "UNKNOWN" || x.orderOutcome === undefined)) return false;
  if (x.runtime.state !== "UNKNOWN" && x.orderOutcome !== undefined && statusFor(x.orderOutcome) !== x.status) return false;
  if (x.runtime.state !== "UNKNOWN" && x.orderOutcome === "UNKNOWN") return false;
  if (x.status === "REFUSED" && x.orderOutcome !== undefined) return false;
  return true;
}

/** Coordinator for deterministic local/replay execution. It never discovers live capabilities. */
export class RuntimeSupervisor {
  private readonly mode: CapabilityMode; private readonly writer: OrderWriter; private readonly persistence: WorkflowPersistence; private readonly clock: () => number; private readonly tails = new Map<string, Promise<void>>();
  constructor(options: RuntimeSupervisorOptions) { if (options.mode !== "SHADOW" && options.mode !== "LOCAL_REPLAY") throw new TypeError("explicit SHADOW or LOCAL_REPLAY mode is required"); if (!options.writer || !options.persistence || !options.clock) throw new TypeError("explicit writer, persistence, and clock are required"); if (typeof options.persistence.compareAndSave !== "function" || (options.persistence as any)[WORKFLOW_PERSISTENCE_CAS_CAPABILITY] !== true) throw new TypeError("workflow persistence CAS capability contract is required"); this.mode = options.mode; this.writer = options.writer; this.persistence = options.persistence; this.clock = options.clock; }
  async arm(input: StartWorkflowInput): Promise<WorkflowReceipt> { return this.serial(input.workflowId, () => this.armOnce(input)); }
  async start(input: StartWorkflowInput): Promise<WorkflowReceipt> { return this.serial(input.workflowId, async () => { const armed = await this.armOnce(input); return armed.status === "READY" ? this.triggerOnce(input.workflowId) : armed; }); }
  private async armOnce(input: StartWorkflowInput): Promise<WorkflowReceipt> { this.validateStart(input); const prior = this.persistence.load(input.workflowId); if (prior) { if (!validRecord(prior, this.clock()) || !(await this.lineageMatches(prior))) throw new Error("RECOVERY_BLOCKED: incomplete or conflicting workflow persistence"); if (prior.mandateId !== input.mandate.mandateId) throw new Error("conflicting mandate for workflow"); return frozen({ ...prior }); } const initial: WorkflowRecord = frozen({ kind: "WORKFLOW_RECEIPT", workflowId: input.workflowId, mandateId: input.mandate.mandateId, version: 0, status: "READY", runtime: createMandateRuntime({ expiresAt: input.mandate.expiresAt }), authorityStatus: input.authorityStatus, mandate: structuredClone(input.mandate), market: structuredClone(input.market), account: structuredClone(input.account), evaluationPolicy: structuredClone(input.evaluationPolicy) }); await this.persistence.compareAndSave(initial, -1); return frozen({ ...initial }); }
  async observeMarket(workflowId: string, market: WorkflowMarketState): Promise<WorkflowReceipt> { return this.serial(workflowId, async () => { const record = await this.require(workflowId); if (record.status !== "READY") return frozen({ ...record }); const now = this.clock(); if (!validEnvelope(market, "market", now) || market.version < record.market.version || market.value.symbol !== record.mandate.symbol || market.value.venue !== record.mandate.venue || market.value.instrument !== record.mandate.instrument) throw new Error("invalid market observation binding"); const next = frozen({ ...record, market: structuredClone(market), version: record.version + 1 }); await this.persistence.compareAndSave(next, record.version); return this.triggerOnce(workflowId); }); }
  async trigger(workflowId: string): Promise<WorkflowReceipt> { return this.serial(workflowId, () => this.triggerOnce(workflowId)); }
  private async triggerOnce(workflowId: string): Promise<WorkflowReceipt> { const record = await this.require(workflowId); if (record.status !== "READY") return frozen({ ...record }); const now = this.clock(); let runtime = transitionOrThrow(record.runtime, { type: "TRIGGER" }, now, "trigger accepted"); runtime = transitionOrThrow(runtime, { type: "VALIDATE" }, now, "validation started"); const result = evaluateMandate({ workflowId, mandateId: record.mandateId, authorityStatus: record.authorityStatus }, record.mandate, runtime, record.market, record.account, record.evaluationPolicy, now); if (result.kind === "EXECUTION_REFUSAL") { runtime = transitionOrThrow(runtime, { type: "REFUSE" }, now, result.code); return this.saveReceipt(record, { status: "REFUSED", runtime, refusalCode: result.code }); } runtime = transitionOrThrow(runtime, { type: "SUBMIT" }, now, "local/replay submission"); const submitted = await this.writer.submit(result as ExecutionIntent, 0); const event = eventFor(submitted.outcome); if (event) runtime = transitionOrThrow(runtime, event, now, `writer outcome ${submitted.outcome}`); return this.saveReceipt(record, { status: statusFor(submitted.outcome), runtime, orderOutcome: submitted.outcome, clientOrderId: submitted.clientOrderId }); }
  async restore(workflowId: string): Promise<WorkflowReceipt> { return this.serial(workflowId, async () => { const record = this.persistence.load(workflowId); const now = this.clock(); if (!record || !validRecord(record, now) || (record.status === "READY" && now >= record.mandate.expiresAt) || !(await this.lineageMatches(record))) throw new Error("RECOVERY_BLOCKED: incomplete or conflicting workflow persistence"); return frozen({ ...record }); }); }
  async reconcile(workflowId: string, event: FillEvent): Promise<WorkflowReceipt> { return this.serial(workflowId, async () => { const record = await this.require(workflowId); if (!record.clientOrderId) throw new Error("RECOVERY_BLOCKED: no persisted clientOrderId"); const order = await this.writer.reconcile(record.clientOrderId, event); let runtime = record.runtime; const target = eventFor(order.outcome); if (target && record.runtime.state !== "UNKNOWN" && target.type !== "ACKNOWLEDGE" && isLegalTransition(record.runtime.state, (target.type === "PARTIAL_FILL" ? "PARTIALLY_FILLED" : target.type === "FILL" ? "FILLED" : target.type === "CANCEL" ? "CANCELLED" : target.type === "FAIL" ? "FAILED" : target.type === "SUBMIT_UNKNOWN" ? "UNKNOWN" : record.runtime.state))) runtime = transitionOrThrow(runtime, target, this.clock(), `reconciled ${event.eventId}`); const changes: any = { status: record.runtime.state === "UNKNOWN" ? "UNKNOWN" : statusFor(order.outcome), runtime, orderOutcome: order.outcome, clientOrderId: order.clientOrderId }; if (record.runtime.state === "UNKNOWN") changes.recoveryStatus = "RECONCILED"; return this.saveReceipt(record, changes); }); }
  private validateStart(input: StartWorkflowInput): void { if (this.mode !== "SHADOW" && this.mode !== "LOCAL_REPLAY") throw new Error("unsupported capability mode"); const now = this.clock(); if (!input || typeof input.workflowId !== "string" || input.workflowId.length === 0 || !validMandate(input.mandate) || input.mandate.workflowId !== input.workflowId || !validEnvelope(input.market, "market", now) || !validEnvelope(input.account, "account", now) || input.market.value.symbol !== input.mandate.symbol || input.market.value.venue !== input.mandate.venue || input.market.value.instrument !== input.mandate.instrument || input.account.value.accountId !== input.mandate.accountId || !validPolicy(input.evaluationPolicy) || !["ACTIVE","SUPERSEDED","REVOKED","CONSUMED"].includes(String(input.authorityStatus))) throw new Error("invalid workflow binding"); }
  private async require(id: string): Promise<WorkflowRecord> { const record = this.persistence.load(id); if (!record || !validRecord(record, this.clock())) throw new Error("RECOVERY_BLOCKED: workflow is not persisted"); if (!(await this.lineageMatches(record))) throw new Error("RECOVERY_BLOCKED: workflow lineage is not persisted"); return record; }
  private async lineageMatches(record: WorkflowRecord): Promise<boolean> {
    if (record.clientOrderId === undefined && record.orderOutcome === undefined) return true;
    if (record.clientOrderId === undefined || record.orderOutcome === undefined) return false;
    const order = this.writer.readReceipt(record.clientOrderId);
    return !!order && order.clientOrderId === record.clientOrderId && order.mandateId === record.mandateId && order.workflowId === record.workflowId && order.symbol === record.mandate.symbol && order.side === (record.mandate.side === "BUY" ? "BUY" : "SELL") && order.method === record.mandate.execution.method && order.accountId === record.mandate.accountId && order.outcome === record.orderOutcome;
  }
  private async saveReceipt(record: WorkflowRecord, changes: Partial<WorkflowReceipt>): Promise<WorkflowReceipt> { const next = frozen({ ...record, ...changes, version: record.version + 1 }); await this.persistence.compareAndSave(next, record.version); return frozen({ ...next }); }
  private async serial<T>(id: string, operation: () => Promise<T>): Promise<T> { const previous = this.tails.get(id) ?? Promise.resolve(); let release!: () => void; const gate = new Promise<void>((resolve) => { release = resolve; }); const token = previous.then(() => gate); this.tails.set(id, token); await previous; try { return await operation(); } finally { release(); if (this.tails.get(id) === token) this.tails.delete(id); } }
}
