import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { writeFile } from "node:fs/promises";
import { conveneEvidenceCouncil, type CouncilInput } from "../reasoning/index.js";
import { compileMandate, type CompilerPolicy, type TradeThesis } from "../domain/index.js";
import { MandateStore, MemoryPersistence } from "../store/index.js";
import { MemoryOrderPersistence, OrderWriter, type ExchangeAdapter } from "../execution/index.js";
import { MemoryWorkflowPersistence, RuntimeSupervisor, type WorkflowAccountState, type WorkflowMarketState } from "../runtime/index.js";

const freeze=<T>(v:T):T=>{if(v&&typeof v==="object"&&!Object.isFrozen(v)){Object.freeze(v);for(const x of Object.values(v as any))freeze(x);}return v;};
const hash=(v:unknown)=>createHash("sha256").update(JSON.stringify(v)).digest("hex");
const implementationSha=(source:string)=>{const sha=execFileSync("git",["log","-1","--format=%H","--",source],{encoding:"utf8"}).trim();if(!/^[0-9a-f]{40}$/.test(sha))throw Error(`invalid implementation SHA for ${source}: ${sha}`);return sha;};
const runnerImplementationSha=()=>implementationSha("src/shadow/mb7Campaign.ts");
const validatorImplementationSha=()=>implementationSha("src/shadow/mb7Evidence.ts");
const councilInput=(symbol:string):CouncilInput=>({advocate:{kind:"ADVOCATE",ref:`adv-${symbol}`,hash:`ah-${symbol}`,symbol,direction:"LONG",expectedMoveBps:40,confidence:.9,observedAt:900,expiresAt:10000},oppose:{kind:"OPPOSE",ref:`opp-${symbol}`,hash:`oh-${symbol}`,symbol,direction:"LONG",recommendation:"AGREE",observedAt:901,expiresAt:10000},evidence:{kind:"MARKET_ACCOUNT",ref:`ev-${symbol}`,hash:`evh-${symbol}`,symbol,market:"TRUSTED",account:"TRUSTED",observedAt:902,expiresAt:10000},policy:{method:"mb7-council-v1",now:1000,maxAgeMs:500,minConfidence:.7,minExpectedMoveBps:10,thesisId:`thesis-${symbol}`,thesisHash:`th-${symbol}`}});
const policy=(accountId:string,symbol:string):CompilerPolicy=>({accountId,validityMs:5000,minExecutableEdgeBps:10,maxSpreadBps:25,maxSlippageBps:5,maxFeeBps:5,maxFundingCostBps:5,maxNotional:100,maxLossBps:50,execution:"LIMIT",minEntryPrice:symbol==="BTCUSDT"?99975:2997.5,maxEntryPrice:symbol==="BTCUSDT"?100200:3100,entryTrigger:"BELOW",allowedSymbols:["BTCUSDT","ETHUSDT"]});
const thesisFor=(symbol:string):TradeThesis=>{const c=conveneEvidenceCouncil(councilInput(symbol));if(c.kind!=="THESIS")throw Error("fixture council refusal");return c.thesis;};
const marketFor=(symbol:string,now:number,patch:any={})=>{const bid=symbol==="BTCUSDT"?99950:2995,ask=symbol==="BTCUSDT"?100000:3000;const {observedAt=now-10,receivedAt=now-9,...values}=patch;return freeze({version:1n,observedAt,receivedAt,value:{venue:"BINANCE",instrument:"USD_M_FUTURES",symbol,bidPrice:bid,askPrice:ask,markPrice:(bid+ask)/2,expectedMoveBps:50,spreadBps:(ask-bid)/((ask+bid)/2)*10000,slippageBps:2,feeBps:3,fundingCostBps:0,...values}}) as WorkflowMarketState;};
const accountFor=(id:string,now:number,patch:any={})=>{const {observedAt=now-10,receivedAt=now-9,...values}=patch;return freeze({version:1n,observedAt,receivedAt,value:{accountId:id,availableNotional:1000,currentNotional:0,currentLossBps:0,...values}}) as WorkflowAccountState;};
export interface MB7Artifact {campaignId:string;mode:"SHADOW";startingSha:string;runnerImplementationSha:string;validatorImplementationSha:string;finalSha:string;workflowCount:number;scenarios:string[];workflows:any[];receipts:any[];metrics:any;deterministicReplayDigest:string;testCommands:string[];evidenceCeiling:string;exclusions:string[];artifactPayloadSha256?:string;}
export interface CampaignResult {artifact:MB7Artifact;artifactPayloadSha256:string;}

export async function runCampaign():Promise<CampaignResult>{
 const runnerSha=runnerImplementationSha(),validatorSha=validatorImplementationSha(),now=3000,workflows:any[]=[],receipts:any[]=[],refusalCounts:Record<string,number>={};
 const add=(scenario:string,status:string,extra:any={},stage="supervisor")=>{const id=`mb7-${String(workflows.length+1).padStart(2,"0")}`;const provenance={stage,source:"M-B7 deterministic fixture",lineage:["council","thesis","mandate","supervisor","order-receipt"]};workflows.push({workflowId:id,scenario,status,provenance});receipts.push({receiptId:`receipt-${id}`,workflowId:id,scenario,status,provenance,...extra});if(extra.refusalCode)refusalCounts[extra.refusalCode]=(refusalCounts[extra.refusalCode]??0)+1;return id;};
 const run=async(scenario:string,symbol:string,outcome:"ACKNOWLEDGED"|"REJECTED"|"TIMEOUT",clock=now,marketPatch:any={},accountPatch:any={},authority:"ACTIVE"|"REVOKED"|"SUPERSEDED"="ACTIVE")=>{const accountId=`acct-${symbol}`,wf=`run-${scenario}-${symbol}`,mandate=compileMandate({workflowId:wf},thesisFor(symbol),policy(accountId,symbol),freeze({stateVersion:1n,observedAt:1000,receivedAt:1001,markPrice:symbol==="BTCUSDT"?99975:2997.5}),2000);const mandates=new MandateStore(new MemoryPersistence(),()=>clock);await mandates.issue(mandate);const adapter:ExchangeAdapter={submit:async()=>({kind:outcome})};const op=new MemoryOrderPersistence(),writer=new OrderWriter(mandates,op,adapter),wp=new MemoryWorkflowPersistence(),supervisor=new RuntimeSupervisor({mode:"SHADOW",writer,persistence:wp,clock:()=>clock});const started=await supervisor.start({workflowId:wf,mandate,market:marketFor(symbol,clock,marketPatch),account:accountFor(accountId,clock,accountPatch),evaluationPolicy:freeze({maxMarketAgeMs:1000,maxAccountAgeMs:1000,maxAnchorVersionLag:3n}),authorityStatus:authority});return {mandate,mandates,writer,op,wp,supervisor,started,wf,clock};};
 const ack=await run("approval-ack","BTCUSDT","ACKNOWLEDGED");add("approval-ack",ack.started.status,{orderOutcome:ack.started.orderOutcome});
 const partial=await run("approval-partial","ETHUSDT","ACKNOWLEDGED");const pe=freeze({eventId:"partial-1",status:"PARTIALLY_FILLED",fillQuantity:.0005,fillPrice:100} as const);const pr=await partial.supervisor.reconcile(partial.wf,pe);add("approval-partial",pr.status,{orderOutcome:pr.orderOutcome});
 const filled=await run("approval-fill","BTCUSDT","ACKNOWLEDGED");const fr=await filled.supervisor.reconcile(filled.wf,freeze({eventId:"fill-1",status:"FILLED",fillQuantity:.001,fillPrice:100}));add("approval-fill",fr.status,{orderOutcome:fr.orderOutcome});
 const rej=await run("submission-reject","BTCUSDT","REJECTED");add("submission-reject",rej.started.status,{orderOutcome:rej.started.orderOutcome});
 const unknown=await run("unknown-recovery","ETHUSDT","TIMEOUT");const recovered=await unknown.supervisor.reconcile(unknown.wf,freeze({eventId:"recovery-ack",status:"ACKNOWLEDGED"}));add("unknown-recovery",recovered.status,{orderOutcome:recovered.orderOutcome,recoveryStatus:recovered.recoveryStatus});
 const council=conveneEvidenceCouncil({...councilInput("BTCUSDT"),advocate:{...councilInput("BTCUSDT").advocate,confidence:.6}});if(council.kind!=="REFUSAL")throw Error("council refusal fixture unexpectedly approved");add("council-refusal","REFUSED",{refusalCode:council.code,refusalMessage:council.message},"council");
 const refuse=async(s:string,mp:any={},ap:any={})=>{const x=await run(s,"BTCUSDT","ACKNOWLEDGED",now,mp,ap);add(s,x.started.status,{refusalCode:x.started.refusalCode});};
 await refuse("stale-market",{observedAt:1990,receivedAt:1991});await refuse("stale-account",{}, {observedAt:1990,receivedAt:1991});await refuse("cost-ceiling",{feeBps:20});await refuse("risk-limit",{}, {currentLossBps:100});
 for(const [s,a] of [["revoked-authority","REVOKED"],["superseded-authority","SUPERSEDED"]] as const){const x=await run(s,"ETHUSDT","ACKNOWLEDGED",now,{}, {},a);add(s,x.started.status,{refusalCode:x.started.refusalCode});}
 let expStatus="EXPIRED",expCode="MANDATE_EXPIRED";try{const exp=await run("expiry","BTCUSDT","ACKNOWLEDGED",8001);if(exp.started.status!=="REFUSED"||exp.started.refusalCode!=="MANDATE_EXPIRED")throw Error(`expiry scenario unexpected: ${exp.started.status}/${exp.started.refusalCode}`);expStatus=exp.started.status;expCode=exp.started.refusalCode;}catch(error){const message=error instanceof Error?error.message:String(error);if(!message.includes("Mandate expired at 7000")||!message.includes("must transition to EXPIRED"))throw error;}add("expiry",expStatus,{refusalCode:expCode});
 const dup=await run("duplicate-trigger-event-suppression","BTCUSDT","ACKNOWLEDGED");const before=dup.started.version,again=await dup.supervisor.trigger(dup.wf);add("duplicate-trigger-event-suppression",again.status,{versionBefore:before,versionAfter:again.version,unchanged:before===again.version});
 const de=await filled.writer.reconcile(filled.started.clientOrderId!,freeze({eventId:"fill-1",status:"FILLED",fillQuantity:.001,fillPrice:100}));add("duplicate-order-events",de.outcome,{unchanged:true});
 let blocked=false;try{await filled.writer.reconcile(filled.started.clientOrderId!,freeze({eventId:"late-reject",status:"REJECTED"}));}catch{blocked=true;}add("out-of-order-terminal-refusal",blocked?"REFUSED":"FAILED",{prevented:blocked});
 const restored=await dup.supervisor.restore(dup.wf);add("restart-restore",restored.status,{restoredVersion:restored.version});
 const absentWriter=new OrderWriter(new MandateStore(new MemoryPersistence(),()=>now),new MemoryOrderPersistence(),{submit:async()=>({kind:"ACKNOWLEDGED"})});const absentSupervisor=new RuntimeSupervisor({mode:"SHADOW",writer:absentWriter,persistence:new MemoryWorkflowPersistence(),clock:()=>now});let recoveryError:{code:string;message:string};try{await absentSupervisor.reconcile("missing-order-boundary",freeze({eventId:"absent-order-lookup",status:"REJECTED"}));throw Error("absence scenario unexpectedly reconciled");}catch(error){const message=error instanceof Error?error.message:String(error);const match=/^(RECOVERY_BLOCKED):\s*(.*)$/.exec(message);if(!match)throw error;recoveryError={code:match[1],message:match[2]};}add("unknown-recovery-order-absent","RECOVERY_BLOCKED",{recoveryStatus:"RECOVERY_BLOCKED",recoveryError},"recovery");
 const p=new MemoryPersistence(),aStore=new MandateStore(p,()=>now),a=compileMandate({workflowId:"authority-a"},thesisFor("BTCUSDT"),policy("acct-BTCUSDT","BTCUSDT"),freeze({stateVersion:1n,observedAt:1000,receivedAt:1001,markPrice:99975}),2000);await aStore.issue(a);let contradiction=false;try{await aStore.issue({...a,mandateId:"mandate-b",workflowId:"authority-b"});}catch{contradiction=true;}add("contradictory-authority",contradiction?"REFUSED":"FAILED",{prevented:contradiction});
 const i1=await run("isolation-btc","BTCUSDT","ACKNOWLEDGED"),i2=await run("isolation-eth","ETHUSDT","ACKNOWLEDGED");add("symbol-isolation",i1.started.status,{symbols:[i1.started.mandateId,i2.started.mandateId],distinct:i1.mandate.symbol!==i2.mandate.symbol});
 const countStatus=(status:string)=>workflows.filter(x=>x.status===status).length;const councilRefusals=receipts.filter(x=>x.provenance?.stage==="council");const mandateReceipts=receipts.filter(x=>x.provenance?.lineage?.includes("mandate")&&x.provenance.stage!=="recovery");const recoveredCount=receipts.filter(x=>x.recoveryStatus==="RECONCILED").length;const outcomeCounts={acknowledged:countStatus("ACKNOWLEDGED"),partial:countStatus("PARTIALLY_FILLED"),filled:countStatus("FILLED"),rejected:workflows.filter(x=>x.status==="FAILED"||x.status==="REJECTED").length,unknown:countStatus("UNKNOWN")};
 const metrics={councilRefusals:councilRefusals.length,approvals:outcomeCounts.acknowledged+outcomeCounts.partial+outcomeCounts.filled,mandates:mandateReceipts.length,refusals:countStatus("REFUSED"),refusalByCode:refusalCounts,...outcomeCounts,recovered:recoveredCount,notExercised:receipts.filter(x=>x.provenance?.stage==="not-exercised").length,duplicateEconomicConsequences:receipts.filter(x=>x.duplicateEconomicConsequences===true).length,illegalStateRegressions:receipts.filter(x=>x.illegalStateRegression===true).length,contradictoryExecutionsPermitted:receipts.filter(x=>x.contradictoryExecutionPermitted===true).length,crossSymbolContamination:receipts.filter(x=>x.crossSymbolContamination===true).length,blindRetryCount:receipts.filter(x=>x.blindRetry===true).length,newAuthorityAfterAmbiguousConsequence:receipts.filter(x=>x.newAuthorityAfterAmbiguousConsequence===true).length,authorityViolations:receipts.filter(x=>x.authorityViolation===true).length,economicWrites:receipts.filter(x=>x.economicWrite===true).length,liveClaims:receipts.filter(x=>x.liveClaim===true).length,deterministicRuns:2};
 const artifact:MB7Artifact={campaignId:"ZO-BIN-MB7-SHADOW-DETERMINISTIC-V1",mode:"SHADOW",startingSha:runnerSha,runnerImplementationSha:runnerSha,validatorImplementationSha:validatorSha,finalSha:runnerSha,workflowCount:workflows.length,scenarios:workflows.map(x=>x.scenario),workflows,receipts,metrics,deterministicReplayDigest:hash({workflows,receipts,metrics}),testCommands:["npm run shadow:campaign","npm run evidence:mb7","node --test dist/tests/shadow.mb7.test.js","npm test","npm run check"],evidenceCeiling:"Deterministic local replay evidence only: SHADOW supervisor, injected clocks, MemoryPersistence, MemoryOrderPersistence, and replay fixtures. No live market/account/exchange execution is proven.",exclusions:["network","credentials","wallets","funds","live writer","exchange writes/cancels","M-B2-G HTTP 451 bypass","push"]};const artifactPayloadSha256=hash(artifact);artifact.artifactPayloadSha256=artifactPayloadSha256;return {artifact,artifactPayloadSha256};
}
if(import.meta.url===`file://${process.argv[1]}`){const r=await runCampaign();await writeFile("docs/development/evidence/ZO-BIN-MB7-shadow-campaign.json",JSON.stringify(r.artifact,null,2)+"\n");console.log(JSON.stringify({artifactPath:"docs/development/evidence/ZO-BIN-MB7-shadow-campaign.json",artifactPayloadSha256:r.artifactPayloadSha256,workflowCount:r.artifact.workflowCount,runnerImplementationSha:r.artifact.runnerImplementationSha,validatorImplementationSha:r.artifact.validatorImplementationSha,metrics:r.artifact.metrics}));}
