import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import type { MB7Artifact } from "./mb7Campaign.js";
const sha=(v:unknown)=>createHash("sha256").update(JSON.stringify(v)).digest("hex");
const scenarios=["approval-ack","approval-partial","approval-fill","submission-reject","unknown-recovery","council-refusal","stale-market","stale-account","cost-ceiling","risk-limit","revoked-authority","superseded-authority","expiry","duplicate-trigger-event-suppression","duplicate-order-events","out-of-order-terminal-refusal","restart-restore","unknown-recovery-order-absent","contradictory-authority","symbol-isolation"];
const invariantKeys=["duplicateEconomicConsequences","illegalStateRegressions","contradictoryExecutionsPermitted","crossSymbolContamination","blindRetryCount","newAuthorityAfterAmbiguousConsequence"] as const;
const topKeys=new Set(["campaignId","mode","startingSha","codeSha","finalSha","workflowCount","scenarios","workflows","receipts","metrics","deterministicReplayDigest","testCommands","evidenceCeiling","exclusions","artifactHash"]);
const workflowKeys=new Set(["workflowId","scenario","status","provenance"]);
const receiptKeys=new Set(["receiptId","workflowId","scenario","status","provenance","orderOutcome","recoveryStatus","refusalCode","refusalMessage","versionBefore","versionAfter","unchanged","prevented","restoredVersion","symbols","distinct","recoveryError"]);
const provenanceKeys=new Set(["stage","source","lineage"]);const errorKeys=new Set(["code","message"]);
const metricKeys=["councilRefusals","approvals","mandates","refusals","refusalByCode","acknowledged","partial","filled","rejected","unknown","recovered","notExercised",...invariantKeys,"authorityViolations","economicWrites","liveClaims","deterministicRuns"];
const exactKeys=(o:unknown,keys:Set<string>)=>!!o&&typeof o==="object"&&!Object.getOwnPropertySymbols(o).length&&Object.keys(o as object).every(k=>keys.has(k));
const count=(ws:any[],s:string)=>ws.filter(w=>w.status===s).length;
export function validateEvidence(value:unknown):boolean{try{
 const a=value as MB7Artifact;if(!exactKeys(a,topKeys)||a.campaignId!=="ZO-BIN-MB7-SHADOW-DETERMINISTIC-V1"||a.mode!=="SHADOW")throw Error("VALIDATION_FAIL");
 if(![a.startingSha,a.codeSha,a.finalSha].every(x=>typeof x==="string"&&/^[0-9a-f]{40}$/.test(x))||a.startingSha!==a.codeSha||a.finalSha!==a.codeSha)throw Error("VALIDATION_FAIL");
 if(!Number.isInteger(a.workflowCount)||a.workflowCount!==scenarios.length||JSON.stringify(a.scenarios)!==JSON.stringify(scenarios)||a.workflows.length!==scenarios.length||a.receipts.length!==scenarios.length)throw Error("VALIDATION_FAIL");
 const ids=new Set<string>();for(const w of a.workflows){if(!exactKeys(w,workflowKeys)||typeof w.workflowId!=="string"||ids.has(w.workflowId)||w.scenario!==scenarios.find(s=>s===w.scenario)||typeof w.status!=="string"||!exactKeys(w.provenance,provenanceKeys)||w.provenance.source!=="M-B7 deterministic fixture"||!Array.isArray(w.provenance.lineage)||w.provenance.lineage.join(",")!=="council,thesis,mandate,supervisor,order-receipt")throw Error("VALIDATION_FAIL");ids.add(w.workflowId);}
 const rids=new Set<string>();for(const r of a.receipts){const w=a.workflows.find(x=>x.workflowId===r.workflowId);if(!exactKeys(r,receiptKeys)||typeof r.receiptId!=="string"||rids.has(r.receiptId)||!w||r.scenario!==w.scenario||r.status!==w.status||!exactKeys(r.provenance,provenanceKeys)||r.provenance.stage!==w.provenance.stage)throw Error("VALIDATION_FAIL");rids.add(r.receiptId);if(r.status==="REFUSED"&&!r.refusalCode&&!(["out-of-order-terminal-refusal","contradictory-authority"] as string[]).includes(r.scenario))throw Error("VALIDATION_FAIL");}
 const by=(s:string)=>a.receipts.find(r=>r.scenario===s);const council=by("council-refusal"),expiry=by("expiry"),absent=by("unknown-recovery-order-absent");if(council?.provenance.stage!=="council"||council.refusalCode!=="THRESHOLD_NOT_MET"||typeof council.refusalMessage!=="string")throw Error("VALIDATION_FAIL");if(expiry?.status!=="EXPIRED"||expiry?.refusalCode!=="MANDATE_EXPIRED"||expiry.provenance.stage!=="supervisor")throw Error("VALIDATION_FAIL");if(absent?.status!=="RECOVERY_BLOCKED"||absent.recoveryStatus!=="RECOVERY_BLOCKED"||absent.provenance.stage!=="recovery"||absent.recoveryError?.code!=="RECOVERY_BLOCKED"||typeof absent.recoveryError.message!=="string")throw Error("VALIDATION_FAIL");
 const m=a.metrics;if(!exactKeys(m,new Set(metricKeys))||!metricKeys.every(k=>typeof m[k as keyof typeof m] === (k==="refusalByCode"?"object":"number")))throw Error("VALIDATION_FAIL");for(const k of invariantKeys)if(m[k]!==0)throw Error("VALIDATION_FAIL");const expected={councilRefusals:a.receipts.filter(r=>r.provenance.stage==="council").length,approvals:count(a.workflows,"ACKNOWLEDGED")+count(a.workflows,"PARTIALLY_FILLED")+count(a.workflows,"FILLED"),mandates:a.receipts.filter(r=>r.provenance.lineage.includes("mandate")&&r.provenance.stage!=="recovery").length,refusals:count(a.workflows,"REFUSED"),acknowledged:count(a.workflows,"ACKNOWLEDGED"),partial:count(a.workflows,"PARTIALLY_FILLED"),filled:count(a.workflows,"FILLED"),rejected:a.workflows.filter(w=>w.status==="FAILED"||w.status==="REJECTED").length,unknown:count(a.workflows,"UNKNOWN"),recovered:a.receipts.filter(r=>r.recoveryStatus==="RECONCILED").length,notExercised:a.receipts.filter(r=>r.provenance.stage==="not-exercised").length,authorityViolations:0,economicWrites:0,liveClaims:0,deterministicRuns:2};for(const [k,v] of Object.entries(expected))if(m[k]!==v)throw Error("VALIDATION_FAIL");
 const refusalByCode:Record<string,number>={};for(const r of a.receipts)if(r.refusalCode)refusalByCode[r.refusalCode]=(refusalByCode[r.refusalCode]??0)+1;if(JSON.stringify(m.refusalByCode)!==JSON.stringify(refusalByCode)||a.deterministicReplayDigest!==sha({workflows:a.workflows,receipts:a.receipts,metrics:a.metrics}))throw Error("VALIDATION_FAIL");const copy={...a};delete copy.artifactHash;return typeof a.artifactHash==="string"&&a.artifactHash===sha(copy);
 }catch{return false;}}
if(import.meta.url===`file://${process.argv[1]}`){const path=process.argv[2]??"docs/development/evidence/ZO-BIN-MB7-shadow-campaign.json";const a=JSON.parse(await readFile(path,"utf8"));if(!validateEvidence(a)){console.error("M-B7 evidence validation failed");process.exit(1);}console.log(JSON.stringify({valid:true,artifactHash:a.artifactHash,workflowCount:a.workflowCount,codeSha:a.codeSha,metrics:a.metrics}));}
