import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import type { MB7Artifact } from "./mb7Campaign.js";
const sha=(v:unknown)=>createHash("sha256").update(JSON.stringify(v)).digest("hex");
const scenarios=new Set(["approval-ack","approval-partial","submission-reject","unknown-recovery","council-refusal","stale-market","stale-account","cost-ceiling","risk-limit","revoked-authority","superseded-authority","expiry","duplicate-trigger-event-suppression","out-of-order-terminal-refusal","restart-restore","unknown-recovery-order-absent","contradictory-authority"]);
export function validateEvidence(value:unknown):boolean { try { const a=value as MB7Artifact; if(!a||a.campaignId!=="ZO-BIN-MB7-SHADOW-DETERMINISTIC-V1"||a.mode!=="SHADOW"||typeof a.codeSha!=="string"||!/^[0-9a-f]{40}$/.test(a.codeSha)||a.startingSha!==a.codeSha||a.finalSha!==a.codeSha||!Number.isInteger(a.workflowCount)||a.workflowCount!==a.workflows.length||a.scenarios.length!==a.workflowCount||a.receipts.length<1||a.metrics.authorityViolations!==0||a.metrics.economicWrites!==0||a.metrics.liveClaims!==0||a.evidenceCeiling.includes("live trading proven")||!a.exclusions.includes("network")||!a.exclusions.includes("credentials")||!a.exclusions.includes("push")) return false;
  const ids=new Set<string>(); for(const w of a.workflows){if(!scenarios.has(w.scenario)||ids.has(w.workflowId))return false;ids.add(w.workflowId);if(w.status==="UNKNOWN_WORKFLOW")return false;} const rids=new Set<string>(); for(const r of a.receipts){if(rids.has(r.receiptId))return false;rids.add(r.receiptId);if(!ids.has(r.workflowId))return false;}
  const refusals=a.workflows.filter((x:any)=>x.status==="REFUSED").length; const notEx=a.workflows.filter((x:any)=>x.status==="NOT_EXERCISED").length; if(a.metrics.refusals!==refusals||a.metrics.notExercised!==notEx) return false;
  const expected={acknowledged:a.workflows.filter((x:any)=>x.status==="ACKNOWLEDGED").length,partial:a.workflows.filter((x:any)=>x.status==="PARTIALLY_FILLED").length,rejected:a.workflows.filter((x:any)=>x.status==="FAILED"||x.status==="REJECTED").length,unknown:a.workflows.filter((x:any)=>x.status==="UNKNOWN").length}; for(const k of Object.keys(expected) as (keyof typeof expected)[]) if(a.metrics[k]!==expected[k]) return false;
  const copy={...a}; delete copy.artifactHash; if(a.artifactHash!==sha(copy)) return false; return true;
 } catch{return false;} }
if(import.meta.url===`file://${process.argv[1]}`){const path=process.argv[2]??"docs/development/evidence/ZO-BIN-MB7-shadow-campaign.json";const a=JSON.parse(await readFile(path,"utf8"));if(!validateEvidence(a)){console.error("M-B7 evidence validation failed");process.exit(1);}console.log(JSON.stringify({valid:true,artifactHash:a.artifactHash,workflowCount:a.workflowCount}));}
