import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { ZeroInfinityService } from '../../dist/src/product/service.js';
import { createReasoningStack } from '../../dist/src/product/reasoningStack.js';
const root=new URL('./worker.mjs',import.meta.url).pathname; const processes=[];
function start(mode,port){const p=spawn(process.execPath,[root,mode,String(port)],{stdio:['ignore','pipe','inherit']});processes.push(p);return new Promise((resolve,reject)=>{p.stdout.once('data',()=>resolve());p.once('error',reject);});}
try {
 await start('http',4311); await start('mcp',4312); await start('council',4313);
 const stack=createReasoningStack({name:'heterogeneous-local',version:'v1',profile:'STANDARD',advocate:{adapter:'openai-compatible',baseUrl:'http://127.0.0.1:11434/v1',model:'llama3.2:1b'},opposer:{adapter:'http-agent',endpoint:'http://127.0.0.1:4311/role'},marketAnalyst:{adapter:'mcp-worker',endpoint:'http://127.0.0.1:4312/mcp',tool:'role_artifact'},council:{adapter:'http-agent',endpoint:'http://127.0.0.1:4313/council'}});
 const service=new ZeroInfinityService({reasoningStack:stack,idFactory:()=>`wf-heterogeneous-${Date.now()}`}); const now=Date.now(); const opportunity={symbol:'BTCUSDT',venue:'BINANCE',product:'USD_M_FUTURES',side:'LONG',paperExecution:{compilerPolicy:{accountId:'paper-byo',validityMs:30000,minExecutableEdgeBps:1,maxSpreadBps:20,maxSlippageBps:1,maxFeeBps:1,maxFundingCostBps:1,maxNotional:100,maxLossBps:100,execution:'LIMIT',minEntryPrice:100000,maxEntryPrice:100000,entryTrigger:'BELOW'},anchor:{stateVersion:1n,observedAt:now,receivedAt:now,markPrice:99950},market:{version:1n,observedAt:now,receivedAt:now,value:{venue:'BINANCE',instrument:'USD_M_FUTURES',symbol:'BTCUSDT',bidPrice:99900,askPrice:100000,markPrice:99950,expectedMoveBps:40,spreadBps:(100/((99900+100000)/2))*10000,slippageBps:0,feeBps:0,fundingCostBps:0}},account:{version:1n,observedAt:now,receivedAt:now,value:{accountId:'paper-byo',availableNotional:100,currentNotional:0,currentLossBps:0}},evaluationPolicy:{maxMarketAgeMs:300000,maxAccountAgeMs:300000,maxAnchorVersionLag:0n},fill:{eventId:'byo-paper-fill',status:'FILLED',fillQuantity:.001,fillPrice:100000}}}; const paper=await service.runPaperLiveWorkflow(opportunity,'heterogeneous-local','v1'); const result=paper.result; if(paper.status!=='FILLED') console.error(JSON.stringify({status:paper.status,reason:paper.reason,workflowStatus:result?.workflow?.status,workflowError:result?.workflow?.error})); assert.equal(paper.status,'FILLED'); const workflowId=paper.workflowId; const record=service.getWorkflow(workflowId); const receipt=service.getReasoningReceipt(workflowId); assert.ok(receipt); assert.equal(receipt.council.provenance?.adapter,'http-council-worker'); assert.equal(record.composition.find(x=>x.role==='OPPOSER')?.adapter,'http-agent:http://127.0.0.1:4311/role'); assert.equal(record.composition.find(x=>x.role==='MARKET_ANALYST')?.adapter,'mcp-worker:http://127.0.0.1:4312/mcp'); assert.equal(record.composition.find(x=>x.role==='COUNCIL')?.adapter,'http-agent:http://127.0.0.1:4313/council'); console.log(JSON.stringify({status:'BYO_TO_PAPER_PASS',fullStack:'HETEROGENEOUS_FULL_COUNCIL_STACK_PASS',workflowId,profile:record.reasoningProfile,composition:record.composition,receiptWorkflowId:receipt.workflowId,receiptHash:receipt.canonicalSha256,paperNoWrite:paper.noWrite,executionStatus:result.workflow.execution?.status,executionOrderOutcome:result.workflow.execution?.orderOutcome,provider:record.composition.find(x=>x.role==='ADVOCATE')?.adapter,deterministicExecutionPath:'compileMandate → RuntimeSupervisor → evaluator → LocalReplay OrderWriter'}));
} finally {for(const p of processes)p.kill('SIGTERM');}
