import { createHash } from "node:crypto";
import { ArtifactKind, ARTIFACT_KINDS, RoleAdapter, RoleArtifact, RoleInvocation, RoleName, ValidationError, ReplayConflictError, cloneFrozen, exactOwnPlain, freezeDeep } from "./types.js";
export type Clock = () => number;
export type Transport = (input: RoleInvocation, signal: AbortSignal) => Promise<unknown>;
const hash = (v: unknown): string => createHash("sha256").update(JSON.stringify(v)).digest("hex");
const schemas: Record<Exclude<ArtifactKind, "MARKET_ACCOUNT"> | "MARKET_ACCOUNT", readonly string[]> = { ADVOCATE: ["kind","ref","hash","symbol","direction","expectedMoveBps","confidence","observedAt","expiresAt"], OPPOSE: ["kind","ref","hash","symbol","direction","recommendation","observedAt","expiresAt"], MARKET_ACCOUNT: ["kind","ref","hash","symbol","market","account","observedAt","expiresAt"] };
const forbidden = new Set(["order","mandate","intent","trade","side","quantity","price","notional"]);
const ROLE_ARTIFACT_KIND: Record<Exclude<RoleName, "COUNCIL">, ArtifactKind> = { ADVOCATE: "ADVOCATE", OPPOSER: "OPPOSE", MARKET_ANALYST: "MARKET_ACCOUNT" };
function validPayload(kind: ArtifactKind, payload: unknown): payload is Readonly<Record<string, unknown>> { if (!exactOwnPlain(payload, schemas[kind], schemas[kind])) return false; const p = payload as Record<string, unknown>; if (Reflect.ownKeys(p).some(k => forbidden.has(String(k)))) return false; if (p.kind !== kind || typeof p.ref !== "string" || typeof p.hash !== "string" || typeof p.symbol !== "string" || typeof p.observedAt !== "number" || typeof p.expiresAt !== "number" || !Number.isFinite(p.observedAt) || !Number.isFinite(p.expiresAt) || p.expiresAt <= p.observedAt) return false; if (kind === "ADVOCATE" && (p.direction !== "LONG" && p.direction !== "SHORT" || typeof p.expectedMoveBps !== "number" || !Number.isFinite(p.expectedMoveBps) || p.expectedMoveBps < 0 || typeof p.confidence !== "number" || !Number.isFinite(p.confidence) || p.confidence < 0 || p.confidence > 1)) return false; if (kind === "OPPOSE" && (p.direction !== "LONG" && p.direction !== "SHORT" || p.recommendation !== "AGREE")) return false; if (kind === "MARKET_ACCOUNT" && (p.market !== "TRUSTED" || p.account !== "TRUSTED")) return false; return true; }
function make(input: RoleInvocation, kind: ArtifactKind, payload: Record<string, unknown>, name: string, independence: "builtin" | "injected" | "external", clock: Clock): RoleArtifact { const base = { workflowId: input.workflowId, invocationId: input.invocationId, role: input.role, kind, payload: cloneFrozen(payload), producedAt: clock(), independence }; return freezeDeep({ ...base, artifactHash: hash(base) }); }
export class BuiltinWorkerAdapter implements RoleAdapter { readonly independence = "builtin" as const; constructor(public readonly name = "builtin-worker-v1", private readonly clock: Clock = () => Date.now()) {} async invoke(input: RoleInvocation): Promise<RoleArtifact> { const symbol = typeof input.opportunity.symbol === "string" ? input.opportunity.symbol : "BTCUSDT"; const t = this.clock(); const common = { ref: input.invocationId, hash: hash(input), symbol, observedAt: t, expiresAt: t + 300000 }; if (input.role === "ADVOCATE") return make(input, "ADVOCATE", { kind: "ADVOCATE", ...common, direction: "LONG", expectedMoveBps: 40, confidence: .8 }, this.name, this.independence, this.clock); if (input.role === "OPPOSER") return make(input, "OPPOSE", { kind: "OPPOSE", ...common, direction: "LONG", recommendation: "AGREE" }, this.name, this.independence, this.clock); if (input.role === "MARKET_ANALYST") return make(input, "MARKET_ACCOUNT", { kind: "MARKET_ACCOUNT", ...common, market: "TRUSTED", account: "TRUSTED" }, this.name, this.independence, this.clock); throw new ValidationError("Council is service-owned"); } }
export abstract class TransportAdapter implements RoleAdapter { abstract readonly independence: "external"; private readonly replay = new Map<string, string>(); constructor(public readonly name: string, protected readonly transport: Transport, private readonly clock: Clock = () => Date.now(), private readonly timeoutMs = 5000) {} async invoke(input: RoleInvocation): Promise<RoleArtifact> { if (input.role === "COUNCIL") throw new ValidationError("external adapters are limited to pre-Council roles"); const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), Math.min(this.timeoutMs, input.timeoutMs)); let raw: unknown; try { raw = await Promise.race([this.transport(input, controller.signal), new Promise<never>((_, reject) => setTimeout(() => reject(new ValidationError("adapter timeout")), Math.min(this.timeoutMs, input.timeoutMs)))]); } catch { throw new ValidationError("external adapter failed or timed out"); } finally { clearTimeout(timeout); } if (!exactOwnPlain(raw, ["workflowId","invocationId","role","kind","payload"], ["workflowId","invocationId","role","kind","payload"])) throw new ValidationError("invalid external artifact envelope"); const x = raw as Record<string, unknown>; if (x.workflowId !== input.workflowId || x.invocationId !== input.invocationId || x.role !== input.role || x.kind !== ROLE_ARTIFACT_KIND[input.role] || (typeof input.opportunity.symbol === "string" && (x.payload as Record<string, unknown>)?.symbol !== input.opportunity.symbol) || typeof x.kind !== "string" || !ARTIFACT_KINDS.includes(x.kind as ArtifactKind) || !validPayload(x.kind as ArtifactKind, x.payload)) throw new ValidationError("external artifact binding or schema invalid"); if (this.replay.has(input.invocationId) && this.replay.get(input.invocationId) !== hash(x)) throw new ReplayConflictError("external invocation replay conflict"); this.replay.set(input.invocationId, hash(x)); return make(input, x.kind as ArtifactKind, x.payload as Record<string, unknown>, this.name, this.independence, this.clock);
} }
export interface OpenAICompatibleEnv { readonly ZI_REASONING_OPENAI_BASE_URL?: string; readonly ZI_REASONING_OPENAI_MODEL?: string; readonly ZI_REASONING_OPENAI_API_KEY?: string; }
const providerConfig = (env: OpenAICompatibleEnv): { readonly baseUrl: string; readonly model: string; readonly apiKey: string } | undefined => {
  const baseUrl = env.ZI_REASONING_OPENAI_BASE_URL?.trim(); const model = env.ZI_REASONING_OPENAI_MODEL?.trim(); const apiKey = env.ZI_REASONING_OPENAI_API_KEY?.trim();
  if (!baseUrl || !model || !apiKey) return undefined;
  try { const url = new URL(baseUrl); if (!["http:", "https:"].includes(url.protocol) || url.username || url.password || url.search || url.hash) return undefined; return { baseUrl: url.toString().replace(/\/$/, ""), model, apiKey }; } catch { return undefined; }
};
const openAITransport = (config: { readonly baseUrl: string; readonly model: string; readonly apiKey: string }): Transport => async (input, signal) => {
  const response = await fetch(`${config.baseUrl}/chat/completions`, { method: "POST", signal, headers: { "content-type": "application/json", authorization: `Bearer ${config.apiKey}` }, body: JSON.stringify({ model: config.model, temperature: 0, messages: [{ role: "system", content: "Return only the requested JSON artifact. Never include orders, mandates, intents, or execution instructions." }, { role: "user", content: JSON.stringify({ workflowId: input.workflowId, invocationId: input.invocationId, role: input.role, symbol: input.opportunity.symbol ?? null, opportunity: input.opportunity }) }] }) });
  if (!response.ok) throw new ValidationError("provider response unavailable");
  const body: unknown = await response.json(); if (!exactOwnPlain(body, ["choices"], ["choices"]) || !Array.isArray(body.choices) || body.choices.length !== 1) throw new ValidationError("provider response malformed");
  const choice = body.choices[0]; if (!exactOwnPlain(choice, ["message"], ["message"]) || !exactOwnPlain(choice.message, ["content"], ["content"]) || typeof choice.message.content !== "string") throw new ValidationError("provider content malformed");
  try { return JSON.parse(choice.message.content) as unknown; } catch { throw new ValidationError("provider artifact is not JSON"); }
};
export function createOpenAICompatibleAdapterFromEnv(env: OpenAICompatibleEnv = process.env, transport?: Transport): OpenAICompatibleModelAdapter | undefined { const config = providerConfig(env); return config ? new OpenAICompatibleModelAdapter("openai-compatible-reasoning-v1", transport ?? openAITransport(config)) : undefined; }

export class OpenAICompatibleModelAdapter extends TransportAdapter { readonly independence = "external" as const; }
export class HttpAgentAdapter extends TransportAdapter { readonly independence = "external" as const; }
export class McpWorkerAdapter extends TransportAdapter { readonly independence = "external" as const; }
