import { createHash } from "node:crypto";
import { isCanonicalBoundedIntent, type BoundedIntent, type OrderOutcome } from "../execution/index.js";
import { cloneFrozen, ProductAccessError } from "./types.js";
export type RuntimeMode = "SHADOW" | "PAPER_LIVE" | "BINANCE_TESTNET" | "LIVE_CONFIRMED";
export type PaperFillStatus = "ACK" | "PARTIAL_FILL" | "FILLED" | "REJECT" | "CANCEL";
export interface PaperFill { readonly fillId: string; readonly quantity: number; readonly price: number; readonly fee: number; readonly status: "ACK" | "PARTIAL_FILL" | "FILLED"; }
export interface PaperAccount { readonly accountId: string; readonly cash: number; readonly equity: number; readonly availableBalance: number; readonly positions: Readonly<Record<string, number>>; readonly realizedPnl: number; readonly unrealizedPnl: number; readonly openOrders: readonly string[]; readonly fills: readonly PaperFill[]; readonly fees: number; readonly funding: number; readonly exposure: number; }
export interface PaperReceipt { readonly kind: "PAPER_ORDER_RECEIPT"; readonly outcome: OrderOutcome; readonly paper: true; readonly simulated: true; readonly topOfBookOnly: true; readonly clientOrderId: string; readonly workflowId: string; readonly reasoningHash?: string; readonly mandateId: string; readonly intentFingerprint: string; readonly marketStateVersion: bigint; readonly economics: Readonly<Record<string, unknown>>; readonly accountTransition: PaperAccount; }
export interface PaperFillModel { readonly status: PaperFillStatus; readonly version: string; readonly partialRatio?: number; readonly price?: number; }
const digest = (value: unknown) => createHash("sha256").update(JSON.stringify(value, (_, v) => typeof v === "bigint" ? `${v}n` : v)).digest("hex");
export class PaperOrderWriter {
  private account: PaperAccount;
  constructor(accountId = "paper-default", cash = 100000, private readonly model: PaperFillModel = { status: "FILLED", version: "paper-top-of-book-v1" }) { if (!Number.isFinite(cash) || cash < 0 || !model.version) throw new Error("invalid paper configuration"); this.account = cloneFrozen({ accountId, cash, equity: cash, availableBalance: cash, positions: {}, realizedPnl: 0, unrealizedPnl: 0, openOrders: [], fills: [], fees: 0, funding: 0, exposure: 0 }); }
  getAccount(): PaperAccount { return cloneFrozen(this.account); }
  submit(intent: BoundedIntent, attempt = 0): Promise<PaperReceipt> { if (!isCanonicalBoundedIntent(intent)) return Promise.reject(new Error("intent is invalid, untrusted, or mutable")); const clientOrderId = `paper-${digest([intent.workflowId, intent.mandateId, attempt]).slice(0, 32)}`; const quantity = intent.quantity ?? intent.notional / intent.price; if (!Number.isFinite(quantity) || quantity <= 0) return Promise.reject(new Error("invalid paper quantity")); const price = this.model.price ?? intent.price; const ratio = this.model.status === "PARTIAL_FILL" ? this.model.partialRatio ?? .5 : 1; const filled = this.model.status === "PARTIAL_FILL" ? quantity * ratio : this.model.status === "FILLED" ? quantity : 0; const outcome: OrderOutcome = this.model.status === "ACK" ? "ACKNOWLEDGED" : this.model.status === "PARTIAL_FILL" ? "PARTIALLY_FILLED" : this.model.status === "FILLED" ? "FILLED" : this.model.status === "REJECT" ? "REJECTED" : "CANCELLED"; if (this.model.status === "PARTIAL_FILL" && !(ratio > 0 && ratio < 1)) return Promise.reject(new Error("partialRatio must be between zero and one")); const fee = filled * price * .0004; const next: PaperAccount = cloneFrozen({ ...this.account, cash: this.account.cash - (intent.side === "BUY" ? filled * price : -filled * price) - fee, equity: this.account.equity - fee, availableBalance: this.account.availableBalance - fee, positions: { ...this.account.positions, [intent.symbol]: (this.account.positions[intent.symbol] ?? 0) + (intent.side === "BUY" ? filled : -filled) }, fills: filled ? [...this.account.fills, { fillId: `${clientOrderId}:fill`, quantity: filled, price, fee, status: this.model.status === "PARTIAL_FILL" ? "PARTIAL_FILL" : "FILLED" as const }] : this.account.fills, fees: this.account.fees + fee, exposure: this.account.exposure + filled * price }); this.account = next; return Promise.resolve(cloneFrozen({ kind: "PAPER_ORDER_RECEIPT", outcome, paper: true, simulated: true, topOfBookOnly: true, clientOrderId, workflowId: intent.workflowId, mandateId: intent.mandateId, intentFingerprint: digest(intent), marketStateVersion: intent.marketStateVersion, economics: { modelVersion: this.model.version, fillStatus: this.model.status, price, requestedQuantity: quantity, filledQuantity: filled }, accountTransition: next })); }
}
export const PAPER_CAPABILITIES = { version: "v1", modes: { shadow: true, paperLive: true, testnet: false, liveConfirmed: false }, evidence: "simulated", topOfBookOnly: true, liveWrites: false } as const;
export function assertSupportedMode(mode: RuntimeMode): RuntimeMode { if (mode === "BINANCE_TESTNET" || mode === "LIVE_CONFIRMED") throw new ProductAccessError("CAPABILITY_DENIED", `${mode} is unavailable; no Binance transport is configured`); return mode; }
