import { handleRequest } from "./http.js";
import { ZeroInfinityService } from "./service.js";
import type { ReasoningReceipt } from "../reasoning/receipt.js";
import type { WorkflowRecord, WorkflowResult } from "./types.js";
import type { AnchorState, CompilerPolicy } from "../domain/index.js";
import type { AdvisoryWorkflowResult } from "./service.js";
export type FetchLike = (url: string, init?: { readonly method?: string; readonly body?: string; readonly headers?: Record<string, string> }) => Promise<{ readonly status: number; json(): Promise<unknown> }>;
export class ZeroInfinityClient { constructor(private readonly fetcher: FetchLike, private readonly base = "") {} private async call<T>(method: string, path: string, body?: unknown): Promise<T> { const response = await this.fetcher(this.base + path, { method, ...(body === undefined ? {} : { body: JSON.stringify(body, (_key, value) => typeof value === "bigint" ? `${value}n` : value), headers: { "content-type": "application/json" } }) }); const value = await response.json(); if (response.status >= 400) throw new Error(`request failed: ${response.status}`); return value as T; } createWorkflow(opportunity: Readonly<Record<string, unknown>>): Promise<WorkflowRecord> { return this.call("POST", "/v1/workflows", opportunity); } submitOpportunity(id: string): Promise<WorkflowResult> { return this.call("POST", `/v1/workflows/${encodeURIComponent(id)}/submit`); } getWorkflow(id: string): Promise<WorkflowRecord> { return this.call("GET", `/v1/workflows/${encodeURIComponent(id)}`); } getMandate(id: string): Promise<unknown> { return this.call("GET", `/v1/workflows/${encodeURIComponent(id)}/mandate`); } getReasoningReceipt(id: string): Promise<ReasoningReceipt> { return this.call("GET", `/v1/workflows/${encodeURIComponent(id)}/receipt`); } getTradeThesis(id: string): Promise<unknown> { return this.call("GET", `/v1/workflows/${encodeURIComponent(id)}/thesis`); } runShadowWorkflow(opportunity: Readonly<Record<string, unknown>>): Promise<unknown> { return this.call("POST", "/v1/shadow", opportunity); } runPaperLiveWorkflow(opportunity: Readonly<Record<string, unknown>>): Promise<unknown> { return this.call("POST", "/v1/paper-live", opportunity); } capabilities(): Promise<unknown> { return this.call("GET", "/capabilities"); } readiness(): Promise<unknown> { return this.call("GET", "/readiness"); } runAdvisoryWorkflow(opportunity: Readonly<Record<string, unknown>>, compilerPolicy: CompilerPolicy, anchor: AnchorState, stackName = "default", stackVersion = "v1"): Promise<AdvisoryWorkflowResult> { return this.call("POST", "/v1/advisory", { opportunity, compilerPolicy, anchor, stackName, stackVersion }); } }
export function serviceFetch(service: ZeroInfinityService): FetchLike { return async (url, init) => { const response = await handleRequest(service, init?.method ?? "GET", new URL(url, "http://localhost").pathname, init?.body === undefined ? undefined : JSON.parse(init.body)); return { status: response.status, json: async () => response.body }; }; }
