import { conveneEvidenceCouncil } from "../reasoning/index.js";
import { createReasoningReceipt, ReasoningReceipt } from "../reasoning/receipt.js";
import type { TradeThesis } from "../reasoning/index.js";
import { BuiltinWorkerAdapter, Clock } from "./adapters.js";
import { cloneFrozen, exactOwnPlain, IndependenceClass, ReasoningStack, ReplayConflictError, RefusalError, RoleArtifact, RoleName, ValidationError, NotFoundError, WorkflowRecord, WorkflowResult, ROLE_NAMES, freezeDeep } from "./types.js";
const workerRoles = ["ADVOCATE", "OPPOSER", "MARKET_ANALYST"] as const;

export interface ServiceOptions { readonly clock?: Clock; readonly idFactory?: () => string; }
export class ZeroInfinityService {
  private readonly stacks = new Map<string, ReasoningStack>(); private readonly workflows = new Map<string, WorkflowRecord>(); private readonly receipts = new Map<string, ReasoningReceipt>(); private readonly theses = new Map<string, unknown>(); private readonly clock: Clock; private readonly ids: () => string;
  constructor(options: ServiceOptions = {}) { this.clock = options.clock ?? (() => Date.now()); let n = 0; this.ids = options.idFactory ?? (() => `wf-${this.clock()}-${++n}`); const b = new BuiltinWorkerAdapter("builtin-worker-v1", this.clock); this.registerStack({ name: "default", version: "v1", bindings: { ADVOCATE: b, OPPOSER: b, MARKET_ANALYST: b, COUNCIL: b }, capabilities: ["reasoning", "shadow", "readiness", "events"] }); }
  registerStack(stack: ReasoningStack): ReasoningStack { if (!exactOwnPlain(stack, ["name","version","bindings","capabilities"])) throw new ValidationError("stack is not canonical"); if (!exactOwnPlain(stack.bindings, ROLE_NAMES, ROLE_NAMES)) throw new ValidationError("stack bindings are not canonical"); for (const role of ROLE_NAMES) { const adapter = stack.bindings[role]; if (!adapter || !Object.prototype.hasOwnProperty.call(adapter, "name") || !Object.prototype.hasOwnProperty.call(adapter, "independence") || typeof adapter.name !== "string" || typeof adapter.independence !== "string" || typeof adapter.invoke !== "function") throw new ValidationError(`mandatory binding is invalid: ${role}`); } if (this.stacks.has(`${stack.name}@${stack.version}`)) throw new ReplayConflictError("stack already registered"); const snapshot = freezeDeep({ name: stack.name, version: stack.version, bindings: Object.freeze({ ...stack.bindings }), capabilities: Object.freeze([...stack.capabilities]) }); this.stacks.set(`${stack.name}@${stack.version}`, snapshot); return snapshot; }
  getStack(name = "default", version = "v1"): ReasoningStack { const stack = this.stacks.get(`${name}@${version}`); if (!stack) throw new ValidationError("stack not found"); return stack; }
  createWorkflow(opportunity: Readonly<Record<string, unknown>>, name = "default", version = "v1"): WorkflowRecord { if (!exactOwnPlain(opportunity, Object.keys(opportunity))) throw new ValidationError("opportunity must be a plain data object"); const stack = this.getStack(name, version); const workflowId = this.ids(); const workflow: WorkflowRecord = { workflowId, stackName: stack.name, stackVersion: stack.version, createdAt: this.clock(), status: "CREATED", opportunity: cloneFrozen(opportunity), composition: ([...[...workerRoles], "COUNCIL"] as RoleName[]).map((role) => ({ role, adapter: stack.bindings[role].name, independence: stack.bindings[role].independence as IndependenceClass })) }; const saved = cloneFrozen(workflow); this.workflows.set(workflowId, saved); return cloneFrozen(saved); }
  async submitOpportunity(workflowId: string): Promise<WorkflowResult> { const prior = this.workflows.get(workflowId); if (!prior) throw new ValidationError("workflow not found"); if (prior.status !== "CREATED") return { workflow: cloneFrozen(prior), ...(prior.thesis ? { thesis: cloneFrozen(prior.thesis) } : {}) }; const stack = this.getStack(prior.stackName, prior.stackVersion); const artifacts: Partial<Record<RoleName, RoleArtifact>> = {}; try { for (const role of workerRoles) { const artifact = await stack.bindings[role].invoke({ workflowId, invocationId: `${workflowId}:${role}`, role, opportunity: prior.opportunity, timeoutMs: 5000 }); if (!artifact || artifact.role !== role || artifact.workflowId !== workflowId || artifact.kind !== (role === "ADVOCATE" ? "ADVOCATE" : role === "OPPOSER" ? "OPPOSE" : "MARKET_ACCOUNT")) throw new ValidationError("role binding failed"); artifacts[role] = artifact; } const a = artifacts.ADVOCATE!; const o = artifacts.OPPOSER!; const m = artifacts.MARKET_ANALYST!; const council = conveneEvidenceCouncil({ advocate: a.payload as never, oppose: o.payload as never, evidence: m.payload as never, policy: { method: "zero-infinity-service-v1", now: this.clock(), maxAgeMs: 300000, minConfidence: .7, minExpectedMoveBps: 10, thesisId: workflowId } }); if (council.kind !== "THESIS") throw new RefusalError(council.message); const thesis = cloneFrozen(council.thesis); const receipt = this.receipt(workflowId, a, o, m, thesis); const complete = cloneFrozen({ ...prior, status: "COMPLETE" as const, thesis, receipt }); this.workflows.set(workflowId, complete); this.theses.set(workflowId, thesis); this.receipts.set(workflowId, receipt); return { workflow: cloneFrozen(complete), thesis: cloneFrozen(thesis) }; } catch (error) { const status: "REFUSE" | "REASONING_INCOMPLETE" = error instanceof RefusalError ? "REFUSE" : "REASONING_INCOMPLETE"; const incomplete = cloneFrozen({ ...prior, status, error: error instanceof Error ? error.message : "role failure" }); this.workflows.set(workflowId, incomplete); return { workflow: cloneFrozen(incomplete) }; } }
  private receipt(id: string, a: RoleArtifact, o: RoleArtifact, m: RoleArtifact, thesis: TradeThesis): ReasoningReceipt { const ref = (x: RoleArtifact) => ({ ref: String(x.payload.ref), hash: String(x.payload.hash), workflowId: id, venue: "BINANCE", product: "USD_M_FUTURES", symbol: String(x.payload.symbol) }); const ar = ref(a), or = ref(o), mr = ref(m); return createReasoningReceipt({ receiptVersion: "ZO-BIN-REASONING-RECEIPT-V2", workflowId: id, createdAt: thesis.createdAt, opportunity: { venue: "BINANCE", product: "USD_M_FUTURES", symbol: String(a.payload.symbol) }, evidence: { evidenceBundleHash: mr.hash, supporting: [ar, mr], opposing: [or] }, analyses: { advocate: ar.ref, oppose: or.ref, market: mr.ref }, council: { decision: "APPROVE", direction: thesis.direction === "SHORT" ? "SHORT" : "LONG", confidence: thesis.confidence, expectedMoveBps: thesis.expectedMove.bps, horizonMs: thesis.horizonMs, strongestSupport: ar.ref, strongestOpposition: or.ref, invalidation: ["stale evidence"], unresolved: [] }, rationale: { method: "zero-infinity-service-v1", claims: [{ claimId: "threshold", statement: "council thresholds are met", supportedBy: [ar.ref], opposedBy: [], assumptions: [] }, { claimId: "evidence", statement: "market evidence is trusted", supportedBy: [mr.ref], opposedBy: [], assumptions: [] }] }, output: { councilDecisionHash: thesis.reasoning.councilDecisionHash, tradeThesisHash: undefined } }); }
  getWorkflow(id: string): WorkflowRecord | undefined { const value = this.workflows.get(id); return value && cloneFrozen(value); }
  getReasoningReceipt(id: string): ReasoningReceipt | undefined { const value = this.receipts.get(id); return value && cloneFrozen(value); }
  getTradeThesis(id: string): unknown { const value = this.theses.get(id); return value && cloneFrozen(value); }
  getCapabilities() { return cloneFrozen({ version: "v1", roles: [...ROLE_NAMES], capabilities: ["reasoning", "shadow", "readiness", "events"], writes: [], authority: false }); }
  getReadiness() { return cloneFrozen({ version: "v1", ready: true, mode: "bounded-local", liveWrites: false, hostedEvidence: false }); }
  async runShadowWorkflow(opportunity: Readonly<Record<string, unknown>>) { const workflow = this.createWorkflow(opportunity); const result = await this.submitOpportunity(workflow.workflowId); return cloneFrozen({ version: "v1", mode: "SHADOW" as const, noWrite: true, workflowId: workflow.workflowId, status: result.workflow.status, result }); }
}
