(() => {
  'use strict';
  const config = window.__ZERO_INFINITY_CONFIG__ || {};
  const HOSTED_RUNTIME = 'https://zero-infinity-projection-store.microcosm.workers.dev';
  const apiBase = typeof config.apiBase === 'string' ? config.apiBase.replace(/\/$/, '') : HOSTED_RUNTIME;
  const $ = (id) => document.getElementById(id);
  const TRY_SESSION_KEY = 'zero-infinity.try.last-result.v1';
  const state = { mode: 'SHADOW', side: 'LONG', workflowId: null, payload: null };
  const stages = [
    ['ARMED', 'ready for a bounded trigger', false], ['TRIGGERED', 'trigger condition observed', false], ['VALIDATING', 'state and policy checks', false], ['SUBMITTING', 'submission boundary', false], ['ACKNOWLEDGED', 'adapter acknowledged', false], ['PARTIALLY_FILLED', 'partial fill recorded', false], ['FILLED', 'terminal: filled', true],
    ['REFUSED', 'terminal: fail closed', true], ['INVALIDATED', 'terminal: invalidated', true], ['EXPIRED', 'terminal: expired', true], ['SUPERSEDED', 'terminal: superseded', true], ['CANCELLED', 'terminal: cancelled', true], ['FAILED', 'terminal: failed', true], ['UNKNOWN', 'terminal: unknown; no blind retry', true]
  ];
  const examples = {
    mcp: { label: 'MCP / tools/list', text: `POST $ZERO_INFINITY_API/mcp\n\n{"jsonrpc":"2.0","id":1,"method":"tools/list"}\n\nTools: get_capabilities · get_readiness · register_reasoning_stack · run_advisory · get_mandate · create_workflow · submit_opportunity · get_reasoning_receipt · get_trade_thesis · run_shadow_workflow · run_paper_live · get_workflow` },
    rest: { label: 'REST / existing routes', text: `GET  /capabilities\nGET  /readiness\nPOST /v1/reasoning-stacks\nPOST /v1/advisory\nPOST /v1/workflows\nPOST /v1/workflows/:workflowId/submit\nGET  /v1/workflows/:workflowId\nGET  /v1/workflows/:workflowId/receipt\nGET  /v1/workflows/:workflowId/thesis\nGET  /v1/workflows/:workflowId/mandate\nPOST /v1/shadow\nPOST /v1/paper-live` },
    sdk: { label: 'SDK / ZeroInfinityClient', text: `const client = new ZeroInfinityClient(fetch, apiBase);\nawait client.createWorkflow(opportunity);\nawait client.submitOpportunity(workflowId);\nawait client.getWorkflow(workflowId);\nawait client.getReasoningReceipt(workflowId);\nawait client.getTradeThesis(workflowId);\nawait client.runShadowWorkflow(opportunity);\nawait client.runPaperLiveWorkflow(opportunity);\nawait client.runAdvisoryWorkflow(opportunity, compilerPolicy, anchor);\nawait client.getMandate(workflowId);\nawait client.capabilities();\nawait client.readiness();` },
    adapters: { label: 'Adapters / role boundary', text: `Bring your own intelligence through stable role contracts.\n\nADVOCATE       your alpha model / agent\nOPPOSER        your risk model / agent\nMARKET_ANALYST your quant / market worker\nCOUNCIL        your adjudication worker\n\nSupported worker boundaries:\nBuiltin · OpenAI-compatible · HTTP Agent · MCP Worker\n\nMCP/REST/SDK = how you call 0-infinity.\nRoleAdapter = how intelligence participates.\nRoleAdapter → validated RoleArtifact → Council → receipt → mandate.\nExternal adapters cannot create theses, mandates, intents, or receipts.` }
  };
  let capabilityPromise;
  async function loadCapabilities() {
    if (capabilityPromise) return capabilityPromise;
    capabilityPromise = fetch(`${apiBase}/capabilities`, { credentials: 'omit' }).then(async (response) => { if (!response.ok) throw new Error(`HTTP ${response.status}`); return response.json(); }).then((capabilities) => {
      const modes = Array.isArray(capabilities.modes) ? capabilities.modes : [];
      document.querySelectorAll('[data-mode]').forEach((button) => { const mode = button.dataset.mode === 'PAPER' ? 'PAPER_LIVE' : button.dataset.mode; const available = modes.includes(mode); button.disabled = !available; button.classList.toggle('disabled', !available); });
      const provider = capabilities.providerBackedReasoning;
      document.querySelectorAll('[data-capability-note]').forEach((note) => { note.textContent = provider?.configured ? `Provider-backed reasoning configured: ${provider.adapter}. Profiles: ${(capabilities.reasoningProfiles || []).join(' · ')}.` : `Provider-backed reasoning not configured. Profiles: ${(capabilities.reasoningProfiles || []).join(' · ')}.`; });
      return capabilities;
    }).catch(() => { document.querySelectorAll('[data-capability-note]').forEach((note) => { note.textContent = 'Capability state unavailable; no mode is enabled by fallback.'; }); document.querySelectorAll('[data-mode]').forEach((button) => { button.disabled = true; button.classList.add('disabled'); }); return null; });
    return capabilityPromise;
  }
  function route() { const hash = location.hash.replace(/^#/, ''); if (hash) return hash.replace(/\/$/, '') || '/'; const path = location.pathname.replace(/^\/0-infinity/, '').replace(/\/$/, '') || '/'; return path; }
  function setActiveRoute(name) { document.querySelectorAll('[data-route]').forEach((link) => link.classList.toggle('active', link.dataset.route === name)); }
  function renderRoute() {
    const current = route();
    const name = current === '/app/integrate' ? 'integrate' : current === '/app/try' ? 'try' : current === '/app/demo' ? 'demo' : null;
    if ($('landing')) $('landing').hidden = Boolean(name);
    if ($('app')) $('app').hidden = !name;
    if (!name) { setActiveRoute(''); document.title = '0∞ / evidence before action'; return; }
    setActiveRoute(name); if ($('route-state')) $('route-state').textContent = name === 'demo' ? 'DEMO / READ-ONLY' : name.toUpperCase();
    if ($('demo-panel')) $('demo-panel').hidden = name !== 'demo'; if ($('integrate-panel')) $('integrate-panel').hidden = name !== 'integrate'; if ($('try-panel')) $('try-panel').hidden = name !== 'try';
    document.title = `0∞ / ${name}`;
    if (name === 'integrate') renderExample('mcp');
    if (name === 'integrate' || name === 'try') void loadCapabilities();
    if (name === 'try') restoreTryResult();
  }
  function addDetail(parent, summary, entries) { const detail = document.createElement('details'); const heading = document.createElement('summary'); heading.textContent = summary; detail.append(heading); const list = document.createElement('dl'); for (const [label, value] of entries) { if (value === undefined || value === null || value === '' || (Array.isArray(value) && value.length === 0)) continue; const term = document.createElement('dt'); term.textContent = label; const desc = document.createElement('dd'); desc.textContent = Array.isArray(value) ? value.map(item => typeof item === 'object' ? JSON.stringify(item) : String(item)).join(' · ') : typeof value === 'object' ? JSON.stringify(value) : String(value); list.append(term, desc); } detail.append(list.children.length ? list : Object.assign(document.createElement('p'), { textContent: 'No value returned.' })); parent.append(detail); }
  function renderStages() { const grid = $('stage-grid'); if (!grid || grid.children.length) return; stages.forEach(([name, description, terminal], index) => { const card = document.createElement('article'); card.className = `stage-card${terminal ? ' terminal' : ''}`; card.innerHTML = `<span class="stage-number">${String(index + 1).padStart(2, '0')}</span><b></b><small></small><em>${terminal ? 'TERMINAL' : 'NON-TERMINAL'}</em>`; card.querySelector('b').textContent = name; card.querySelector('small').textContent = description; grid.append(card); }); }
  function renderExample(key) { const example = examples[key]; if (!$('code-label') || !$('code-example')) return; $('code-label').textContent = example.label; $('code-example').textContent = example.text; document.querySelectorAll('[data-tab]').forEach((tab) => { const active = tab.dataset.tab === key; tab.classList.toggle('active', active); tab.setAttribute('aria-selected', active ? 'true' : 'false'); tab.setAttribute('tabindex', active ? '0' : '-1'); }); $('integration-code-panel')?.setAttribute('aria-labelledby', `tab-${key}`); }
  function setStatus(text, kind = 'neutral') { $('api-state').textContent = text; $('api-state').className = `status ${kind}`; }
  function setSequence(step, outcome = 'Awaiting bounded workflow.') { const items = $('result-sequence').querySelectorAll('li'); items.forEach((item, i) => item.classList.toggle('current', i === step)); items[0].querySelector('small').textContent = `POST /v1/${state.mode === 'PAPER' ? 'paper-live' : 'shadow'} · ${state.side} · BTCUSDT`; items[1].querySelector('small').textContent = step > 0 ? 'Service returned a bounded workflow result.' : 'Awaiting bounded workflow.'; items[2].querySelector('small').textContent = outcome; }
  function findText(value, keys) { if (!value || typeof value !== 'object') return null; for (const key of keys) if (typeof value[key] === 'string' || typeof value[key] === 'number') return value[key]; for (const child of Object.values(value)) { const found = findText(child, keys); if (found !== null) return found; } return null; }
  function findObject(value, keys) { if (!value || typeof value !== 'object') return null; for (const key of keys) if (value[key] && typeof value[key] === 'object') return value[key]; for (const child of Object.values(value)) { const found = findObject(child, keys); if (found) return found; } return null; }
  function renderStructuredDetails(payload) { const receipt = findObject(payload, ['receipt']); const result = payload?.result && typeof payload.result === 'object' ? payload.result : {}; const thesis = result?.thesis && typeof result.thesis === 'object' ? result.thesis : findObject(payload, ['thesis']) || {}; const council = receipt?.council || {}; const evidence = receipt?.evidence || {}; const analyses = receipt?.analyses || {}; const output = receipt?.output || {}; const rationale = receipt?.rationale || {}; const container = $('narrative-details'); container.replaceChildren(); addDetail(container, 'Advocate support', [['artifact reference', analyses.advocate], ['strongest support', council.strongestSupport]]); addDetail(container, 'Opposer challenge', [['artifact reference', analyses.oppose], ['strongest opposition', council.strongestOpposition]]); addDetail(container, 'Market Analyst evidence', [['artifact reference', analyses.market]]); addDetail(container, 'Council decision / confidence', [['decision', council.decision], ['direction', council.direction], ['confidence', council.confidence], ['expected move (bps)', council.expectedMoveBps], ['horizon (ms)', council.horizonMs]]); const refLabel = (ref) => ref && typeof ref === 'object' ? `${ref.ref || 'reference'} · ${ref.hash || 'hash unavailable'}` : ref; addDetail(container, 'Supporting evidence', [['references', (evidence.supporting || []).map(refLabel)], ['bundle hash', evidence.evidenceBundleHash]]); addDetail(container, 'Opposing evidence', [['references', (evidence.opposing || []).map(refLabel)]]); addDetail(container, 'Assumptions', [['claim assumptions', Array.isArray(rationale.claims) ? rationale.claims.flatMap(claim => claim.assumptions || []) : []]]); addDetail(container, 'Unresolved uncertainty', [['items', council.unresolved]]); addDetail(container, 'Invalidation', [['conditions', council.invalidation]]); addDetail(container, 'Hashes', [['evidence bundle', evidence.evidenceBundleHash], ['council decision', output.councilDecisionHash], ['trade thesis', output.tradeThesisHash], ['reasoning receipt', receipt?.canonicalSha256]]); addDetail(container, 'Economics', [['thesis economics', thesis.economics], ['returned edge (bps)', findText(payload, ['executableEdgeBps', 'edgeBps'])], ['returned costs (bps)', findText(payload, ['costBps', 'costsBps'])], ['required edge (bps)', findText(payload, ['requiredEdgeBps', 'requiredBps'])]]); addDetail(container, 'Paper receipt', [['mode', payload?.mode], ['no-write', payload?.noWrite], ['outcome', payload?.paperReceipt?.outcome], ['simulated', payload?.paperReceipt?.simulated]]); $('narrative').hidden = false; }
  function renderResult(payload) { state.payload = payload; state.workflowId = findText(payload, ['workflowId']); const status = findText(payload, ['status', 'outcome', 'decision']) || 'RETURNED'; const refusal = String(status).toUpperCase().includes('REFUS') || String(status).toUpperCase().includes('COLLAPSED'); setStatus('API · connected', 'good'); setSequence(2, String(status)); $('outcome').className = `outcome ${refusal ? 'refusal-outcome' : ''}`; $('outcome').querySelector('strong').textContent = refusal ? `REFUSED · ${status}` : `ACTUAL · ${status}`; $('outcome').querySelector('p').textContent = payload?.noWrite === true ? 'No exchange write occurred. The service returned this bounded result.' : 'Returned by the configured service. Verify authority before acting.'; $('receipt-link').disabled = !state.workflowId; $('raw-link').disabled = false; $('edge-value').textContent = findText(payload, ['executableEdgeBps', 'edgeBps']) ?? '—'; $('cost-value').textContent = findText(payload, ['costBps', 'costsBps']) ?? '—'; $('threshold-value').textContent = findText(payload, ['requiredEdgeBps', 'requiredBps']) ?? '—'; renderStructuredDetails(payload); $('raw-json').textContent = JSON.stringify(payload, null, 2); try { sessionStorage.setItem(TRY_SESSION_KEY, JSON.stringify(payload)); } catch { /* storage is optional; the live result remains visible */ } }
  function restoreTryResult() { try { const saved = sessionStorage.getItem(TRY_SESSION_KEY); if (saved) renderResult(JSON.parse(saved)); } catch { sessionStorage.removeItem(TRY_SESSION_KEY); } }
  async function callWorkflow(event) { event.preventDefault(); const endpoint = state.mode === 'PAPER' ? '/v1/paper-live' : '/v1/shadow'; setStatus('CALLING · no-write', 'working'); setSequence(1); $('run-demo').disabled = true; try { const response = await fetch(`${apiBase}${endpoint}`, { method: 'POST', headers: { 'content-type': 'application/json', accept: 'application/json' }, credentials: 'omit', body: JSON.stringify({ symbol: $('symbol').value, side: state.side }) }); const payload = await response.json(); if (!response.ok) throw new Error(`HTTP ${response.status}`); renderResult(payload); } catch (error) { setStatus('API · unavailable', 'bad'); setSequence(0, `No result: ${error.message}`); $('outcome').querySelector('strong').textContent = 'NO RESULT'; $('outcome').querySelector('p').textContent = 'The configured REST service did not respond. No fallback or fabricated result is shown.'; } finally { $('run-demo').disabled = false; } }
  renderStages(); renderRoute(); window.addEventListener('hashchange', renderRoute); $('demo-form')?.addEventListener('submit', callWorkflow); document.querySelectorAll('[data-side]').forEach((button) => button.addEventListener('click', () => { state.side = button.dataset.side; document.querySelectorAll('[data-side]').forEach((b) => { b.classList.toggle('selected', b === button); b.setAttribute('aria-pressed', b === button ? 'true' : 'false'); }); })); document.querySelectorAll('[data-mode]').forEach((button) => button.addEventListener('click', () => { state.mode = button.dataset.mode; document.querySelectorAll('[data-mode]').forEach((b) => b.classList.toggle('selected', b === button)); $('run-demo').textContent = `Run ${state.mode} →`; })); document.querySelectorAll('[data-tab]').forEach((tab) => { tab.addEventListener('click', () => renderExample(tab.dataset.tab)); tab.addEventListener('keydown', (event) => { if (!['ArrowRight', 'ArrowDown', 'ArrowLeft', 'ArrowUp'].includes(event.key)) return; const tabs = [...document.querySelectorAll('[data-tab]')]; const index = tabs.indexOf(tab); const next = tabs[(index + (event.key === 'ArrowRight' || event.key === 'ArrowDown' ? 1 : -1) + tabs.length) % tabs.length]; event.preventDefault(); next.focus(); renderExample(next.dataset.tab); }); }); $('copy-code')?.addEventListener('click', async () => { try { await navigator.clipboard.writeText($('code-example').textContent); $('copy-code').textContent = 'Copied'; setTimeout(() => { $('copy-code').textContent = 'Copy'; }, 1200); } catch { $('copy-code').textContent = 'Select manually'; } }); $('receipt-link')?.addEventListener('click', async () => { if (!state.workflowId) return; try { const response = await fetch(`${apiBase}/v1/workflows/${encodeURIComponent(state.workflowId)}/receipt`, { credentials: 'omit' }); const payload = await response.json(); $('raw-json').textContent = JSON.stringify(payload, null, 2); $('raw-json').hidden = false; } catch { $('raw-json').textContent = 'Receipt unavailable from configured service.'; $('raw-json').hidden = false; } }); $('raw-link')?.addEventListener('click', () => { $('raw-json').hidden = !$('raw-json').hidden; });
})();
