(() => {
  'use strict';
  const config = window.__ZERO_INFINITY_CONFIG__ || {};
  const HOSTED_RUNTIME = 'https://http--zero-infinity-runtime--tw56snbf4tjj.code.run';
  const apiBase = typeof config.apiBase === 'string' ? config.apiBase.replace(/\/$/, '') : HOSTED_RUNTIME;
  const $ = (id) => document.getElementById(id);
  const state = { mode: 'SHADOW', side: 'LONG', workflowId: null, payload: null };
  const stages = [
    ['ARMED', 'ready for a bounded trigger', false], ['TRIGGERED', 'trigger condition observed', false], ['VALIDATING', 'state and policy checks', false], ['SUBMITTING', 'submission boundary', false], ['ACKNOWLEDGED', 'adapter acknowledged', false], ['PARTIALLY_FILLED', 'partial fill recorded', false], ['FILLED', 'terminal: filled', true],
    ['REFUSED', 'terminal: fail closed', true], ['INVALIDATED', 'terminal: invalidated', true], ['EXPIRED', 'terminal: expired', true], ['SUPERSEDED', 'terminal: superseded', true], ['CANCELLED', 'terminal: cancelled', true], ['FAILED', 'terminal: failed', true], ['UNKNOWN', 'terminal: unknown; no blind retry', true]
  ];
  const examples = {
    mcp: { label: 'MCP / tools/list', text: `POST $ZERO_INFINITY_API/mcp\n\n{"jsonrpc":"2.0","id":1,"method":"tools/list"}\n\nTools: get_capabilities · get_readiness · create_workflow · submit_opportunity · get_reasoning_receipt · get_trade_thesis · run_shadow_workflow · run_paper_live · get_workflow` },
    rest: { label: 'REST / existing routes', text: `GET  /capabilities\nGET  /readiness\nPOST /v1/workflows\nPOST /v1/workflows/:workflowId/submit\nGET  /v1/workflows/:workflowId\nGET  /v1/workflows/:workflowId/receipt\nGET  /v1/workflows/:workflowId/thesis\nPOST /v1/shadow\nPOST /v1/paper-live` },
    sdk: { label: 'SDK / ZeroInfinityClient', text: `const client = new ZeroInfinityClient(fetch, apiBase);\nawait client.createWorkflow(opportunity);\nawait client.submitOpportunity(workflowId);\nawait client.getWorkflow(workflowId);\nawait client.getReasoningReceipt(workflowId);\nawait client.getTradeThesis(workflowId);\nawait client.runShadowWorkflow(opportunity);\nawait client.runPaperLiveWorkflow(opportunity);\nawait client.capabilities();\nawait client.readiness();` },
    adapters: { label: 'Adapters / role boundary', text: `Role names: ADVOCATE · OPPOSER · MARKET_ANALYST · COUNCIL\nArtifact kinds: ADVOCATE · OPPOSE · MARKET_ACCOUNT\nIndependence: builtin · injected · external\n\nAdapters produce bounded artifacts. External adapters are limited to pre-Council roles; the browser does not invoke them.` }
  };
  function route() { const raw = location.hash.replace(/^#/, '') || location.pathname; return raw.replace(/\/$/, '') || '/'; }
  function setActiveRoute(name) { document.querySelectorAll('[data-route]').forEach((link) => link.classList.toggle('active', link.dataset.route === name)); }
  function renderRoute() {
    const current = route();
    const name = current === '/app/integrate' ? 'integrate' : current === '/app/try' ? 'try' : current === '/app/demo' ? 'demo' : null;
    $('landing').hidden = Boolean(name); $('app').hidden = !name;
    if (!name) { setActiveRoute(''); document.title = '0∞ / evidence before action'; return; }
    setActiveRoute(name); $('route-state').textContent = name === 'demo' ? 'DEMO / READ-ONLY' : name.toUpperCase();
    $('demo-panel').hidden = name !== 'demo'; $('integrate-panel').hidden = name !== 'integrate'; $('try-panel').hidden = name !== 'try';
    document.title = `0∞ / ${name}`;
    if (name === 'integrate') renderExample('mcp');
  }
  function addDetail(parent, summary, entries) { const detail = document.createElement('details'); const heading = document.createElement('summary'); heading.textContent = summary; detail.append(heading); const list = document.createElement('dl'); for (const [label, value] of entries) { if (value === undefined || value === null || value === '' || (Array.isArray(value) && value.length === 0)) continue; const term = document.createElement('dt'); term.textContent = label; const desc = document.createElement('dd'); desc.textContent = Array.isArray(value) ? value.map(item => typeof item === 'object' ? JSON.stringify(item) : String(item)).join(' · ') : typeof value === 'object' ? JSON.stringify(value) : String(value); list.append(term, desc); } detail.append(list.children.length ? list : Object.assign(document.createElement('p'), { textContent: 'No value returned.' })); parent.append(detail); }
  function renderStages() { const grid = $('stage-grid'); if (grid.children.length) return; stages.forEach(([name, description, terminal], index) => { const card = document.createElement('article'); card.className = `stage-card${terminal ? ' terminal' : ''}`; card.innerHTML = `<span class="stage-number">${String(index + 1).padStart(2, '0')}</span><b></b><small></small><em>${terminal ? 'TERMINAL' : 'NON-TERMINAL'}</em>`; card.querySelector('b').textContent = name; card.querySelector('small').textContent = description; grid.append(card); }); }
  function renderExample(key) { const example = examples[key]; $('code-label').textContent = example.label; $('code-example').textContent = example.text; document.querySelectorAll('[data-tab]').forEach((tab) => { const active = tab.dataset.tab === key; tab.classList.toggle('active', active); tab.setAttribute('aria-selected', active ? 'true' : 'false'); }); }
  function setStatus(text, kind = 'neutral') { $('api-state').textContent = text; $('api-state').className = `status ${kind}`; }
  function setSequence(step, outcome = 'Awaiting bounded workflow.') { const items = $('result-sequence').querySelectorAll('li'); items.forEach((item, i) => item.classList.toggle('current', i === step)); items[0].querySelector('small').textContent = `POST /v1/${state.mode === 'PAPER' ? 'paper-live' : 'shadow'} · ${state.side} · BTCUSDT`; items[1].querySelector('small').textContent = step > 0 ? 'Service returned a bounded workflow result.' : 'Awaiting bounded workflow.'; items[2].querySelector('small').textContent = outcome; }
  function findText(value, keys) { if (!value || typeof value !== 'object') return null; for (const key of keys) if (typeof value[key] === 'string' || typeof value[key] === 'number') return value[key]; for (const child of Object.values(value)) { const found = findText(child, keys); if (found !== null) return found; } return null; }
  function findObject(value, keys) { if (!value || typeof value !== 'object') return null; for (const key of keys) if (value[key] && typeof value[key] === 'object') return value[key]; for (const child of Object.values(value)) { const found = findObject(child, keys); if (found) return found; } return null; }
  function renderStructuredDetails(payload) { const receipt = findObject(payload, ['receipt']); const result = payload?.result && typeof payload.result === 'object' ? payload.result : {}; const thesis = result?.thesis && typeof result.thesis === 'object' ? result.thesis : findObject(payload, ['thesis']) || {}; const council = receipt?.council || {}; const evidence = receipt?.evidence || {}; const analyses = receipt?.analyses || {}; const output = receipt?.output || {}; const rationale = receipt?.rationale || {}; const container = $('narrative-details'); container.replaceChildren(); addDetail(container, 'Advocate support', [['artifact reference', analyses.advocate], ['strongest support', council.strongestSupport]]); addDetail(container, 'Opposer challenge', [['artifact reference', analyses.oppose], ['strongest opposition', council.strongestOpposition]]); addDetail(container, 'Market Analyst evidence', [['artifact reference', analyses.market]]); addDetail(container, 'Council decision / confidence', [['decision', council.decision], ['direction', council.direction], ['confidence', council.confidence], ['expected move (bps)', council.expectedMoveBps], ['horizon (ms)', council.horizonMs]]); const refLabel = (ref) => ref && typeof ref === 'object' ? `${ref.ref || 'reference'} · ${ref.hash || 'hash unavailable'}` : ref; addDetail(container, 'Supporting evidence', [['references', (evidence.supporting || []).map(refLabel)], ['bundle hash', evidence.evidenceBundleHash]]); addDetail(container, 'Opposing evidence', [['references', (evidence.opposing || []).map(refLabel)]]); addDetail(container, 'Assumptions', [['claim assumptions', Array.isArray(rationale.claims) ? rationale.claims.flatMap(claim => claim.assumptions || []) : []]]); addDetail(container, 'Unresolved uncertainty', [['items', council.unresolved]]); addDetail(container, 'Invalidation', [['conditions', council.invalidation]]); addDetail(container, 'Hashes', [['evidence bundle', evidence.evidenceBundleHash], ['council decision', output.councilDecisionHash], ['trade thesis', output.tradeThesisHash], ['reasoning receipt', receipt?.canonicalSha256]]); addDetail(container, 'Economics', [['thesis economics', thesis.economics], ['returned edge (bps)', findText(payload, ['executableEdgeBps', 'edgeBps'])], ['returned costs (bps)', findText(payload, ['costBps', 'costsBps'])], ['required edge (bps)', findText(payload, ['requiredEdgeBps', 'requiredBps'])]]); addDetail(container, 'Paper receipt', [['mode', payload?.mode], ['no-write', payload?.noWrite], ['outcome', payload?.paperReceipt?.outcome], ['simulated', payload?.paperReceipt?.simulated]]); $('narrative').hidden = false; }
  function renderResult(payload) { state.payload = payload; state.workflowId = findText(payload, ['workflowId']); const status = findText(payload, ['status', 'outcome', 'decision']) || 'RETURNED'; const refusal = String(status).toUpperCase().includes('REFUS') || String(status).toUpperCase().includes('COLLAPSED'); setStatus('API · connected', 'good'); setSequence(2, String(status)); $('outcome').className = `outcome ${refusal ? 'refusal-outcome' : ''}`; $('outcome').querySelector('strong').textContent = refusal ? `REFUSED · ${status}` : `ACTUAL · ${status}`; $('outcome').querySelector('p').textContent = payload?.noWrite === true ? 'No exchange write occurred. The service returned this bounded result.' : 'Returned by the configured service. Verify authority before acting.'; $('receipt-link').disabled = !state.workflowId; $('raw-link').disabled = false; $('edge-value').textContent = findText(payload, ['executableEdgeBps', 'edgeBps']) ?? '—'; $('cost-value').textContent = findText(payload, ['costBps', 'costsBps']) ?? '—'; $('threshold-value').textContent = findText(payload, ['requiredEdgeBps', 'requiredBps']) ?? '—'; renderStructuredDetails(payload); $('raw-json').textContent = JSON.stringify(payload, null, 2); }
  async function callWorkflow(event) { event.preventDefault(); const endpoint = state.mode === 'PAPER' ? '/v1/paper-live' : '/v1/shadow'; setStatus('CALLING · no-write', 'working'); setSequence(1); $('run-demo').disabled = true; try { const response = await fetch(`${apiBase}${endpoint}`, { method: 'POST', headers: { 'content-type': 'application/json', accept: 'application/json' }, credentials: 'omit', body: JSON.stringify({ symbol: $('symbol').value, side: state.side }) }); const payload = await response.json(); if (!response.ok) throw new Error(`HTTP ${response.status}`); renderResult(payload); } catch (error) { setStatus('API · unavailable', 'bad'); setSequence(0, `No result: ${error.message}`); $('outcome').querySelector('strong').textContent = 'NO RESULT'; $('outcome').querySelector('p').textContent = 'The configured REST service did not respond. No fallback or fabricated result is shown.'; } finally { $('run-demo').disabled = false; } }
  renderStages(); renderRoute(); window.addEventListener('hashchange', renderRoute); $('demo-form').addEventListener('submit', callWorkflow); document.querySelectorAll('[data-side]').forEach((button) => button.addEventListener('click', () => { state.side = button.dataset.side; document.querySelectorAll('[data-side]').forEach((b) => { b.classList.toggle('selected', b === button); b.setAttribute('aria-pressed', b === button ? 'true' : 'false'); }); })); document.querySelectorAll('[data-mode]').forEach((button) => button.addEventListener('click', () => { state.mode = button.dataset.mode; document.querySelectorAll('[data-mode]').forEach((b) => b.classList.toggle('selected', b === button)); $('run-demo').textContent = `Run ${state.mode} →`; })); document.querySelectorAll('[data-tab]').forEach((tab) => tab.addEventListener('click', () => renderExample(tab.dataset.tab))); $('copy-code').addEventListener('click', async () => { try { await navigator.clipboard.writeText($('code-example').textContent); $('copy-code').textContent = 'Copied'; setTimeout(() => { $('copy-code').textContent = 'Copy'; }, 1200); } catch { $('copy-code').textContent = 'Select manually'; } }); $('receipt-link').addEventListener('click', async () => { if (!state.workflowId) return; try { const response = await fetch(`${apiBase}/v1/workflows/${encodeURIComponent(state.workflowId)}/receipt`, { credentials: 'omit' }); const payload = await response.json(); $('raw-json').textContent = JSON.stringify(payload, null, 2); $('raw-json').hidden = false; } catch { $('raw-json').textContent = 'Receipt unavailable from configured service.'; $('raw-json').hidden = false; } }); $('raw-link').addEventListener('click', () => { $('raw-json').hidden = !$('raw-json').hidden; });
})();
