(() => {
  'use strict';
  const config = window.__ZERO_INFINITY_CONFIG__ || {};
  const HOSTED_RUNTIME = 'https://zero-infinity-projection-store.microcosm.workers.dev';
  const apiBase = typeof config.apiBase === 'string' ? config.apiBase.replace(/\/$/, '') : HOSTED_RUNTIME;
  const $ = (id) => document.getElementById(id);
  const TRY_SESSION_KEY = 'zero-infinity.try.last-result.v2';
  const state = { mode: 'ADVISORY', side: 'LONG', payload: null, workflowId: null };
  const FIVE_STAGE_NAMES = ['OPPORTUNITY', 'CHALLENGE', 'JUDGMENT', 'AUTHORITY', 'REALITY'];
  const TERMINAL_CODES = ['EDGE_COLLAPSED', 'MANDATE_EXPIRED', 'EXECUTION_REFUSED', 'NO_MANDATE'];
  const examples = {
    mcp: { label: 'MCP / five-stage call', text: `POST $ZERO_INFINITY_API/mcp\n\n{"jsonrpc":"2.0","id":1,"method":"run_advisory","params":{"opportunity":{...},"compilerPolicy":{...},"anchor":{...}}}\n\n→ mandate issued or refusal` },
    rest: { label: 'REST / five-stage call', text: `POST /v1/advisory\n\n{\n  "opportunity": { "symbol": "BTCUSDT", "venue": "BINANCE", "product": "USD_M_FUTURES" },\n  "compilerPolicy": { ... },\n  "anchor": { ... }\n}\n\n→ ADVISORY · MANDATE_ISSUED or REFUSED` },
    sdk: { label: 'SDK / five-stage call', text: `const result = await client.runAdvisoryWorkflow(\n  opportunity,\n  compilerPolicy,\n  anchor,\n);\n\n// result.mandate is bounded and verifiable\n// result.noWrite === true` },
  };
  function route() { const path = location.pathname.replace(/^\/0-infinity/, '').replace(/\/$/, '') || '/'; return path; }
  function setActiveRoute(name) { document.querySelectorAll('[data-route]').forEach((link) => link.classList.toggle('active', link.dataset.route === name)); }
  function renderRoute() {
    const current = route(); const name = current === '/app/integrate' ? 'integrate' : current === '/app/try' ? 'try' : current === '/app/demo' ? 'demo' : null;
    if ($('landing')) $('landing').hidden = Boolean(name); if ($('app')) $('app').hidden = !name;
    if (!name) { setActiveRoute(''); return; }
    setActiveRoute(name); document.title = `0∞ / ${name}`;
    if (name === 'integrate') { setTask('use'); renderExample('mcp'); void loadCapabilities(); }
    if (name === 'try') { void loadCapabilities(); restoreTryResult(); }
  }
  function setTask(task) {
    document.querySelectorAll('[data-task]').forEach((button) => { const active = button.dataset.task === task; button.classList.toggle('active', active); button.setAttribute('aria-selected', active ? 'true' : 'false'); button.tabIndex = active ? 0 : -1; });
    document.querySelectorAll('[data-task-content]').forEach((panel) => { panel.hidden = panel.dataset.taskContent !== task; });
    const active = document.querySelector(`[data-task="${task}"]`); if (active) $('task-panel')?.setAttribute('aria-labelledby', active.id);
  }
  function renderExample(key) {
    const example = examples[key]; if (!$('code-label') || !$('code-example') || !example) return;
    $('code-label').textContent = example.label; $('code-example').textContent = example.text;
    document.querySelectorAll('[data-tab]').forEach((tab) => { const active = tab.dataset.tab === key; tab.classList.toggle('active', active); tab.setAttribute('aria-selected', active ? 'true' : 'false'); tab.tabIndex = active ? 0 : -1; });
    $('code-panel')?.setAttribute('aria-labelledby', `tab-${key}`);
  }
  let capabilityPromise;
  async function loadCapabilities() {
    if (capabilityPromise) return capabilityPromise;
    capabilityPromise = fetch(`${apiBase}/capabilities`, { credentials: 'omit' }).then(async (response) => { if (!response.ok) throw new Error(`HTTP ${response.status}`); return response.json(); }).then((capabilities) => {
      const modes = Array.isArray(capabilities.modes) ? capabilities.modes : [];
      document.querySelectorAll('[data-mode]').forEach((button) => { const mode = button.dataset.mode === 'PAPER' ? 'PAPER_LIVE' : button.dataset.mode; const enabled = mode === 'ADVISORY' || modes.includes(mode); button.disabled = !enabled; button.classList.toggle('disabled', !enabled); });
      document.querySelectorAll('[data-capability-note]').forEach((note) => { note.textContent = capabilities.providerBackedReasoning?.configured ? `Provider-backed reasoning: ${capabilities.providerBackedReasoning.adapter}. Profiles: ${(capabilities.reasoningProfiles || []).join(' · ')}.` : `Builtin reasoning available. Profiles: ${(capabilities.reasoningProfiles || []).join(' · ')}.`; }); return capabilities;
    }).catch(() => { document.querySelectorAll('[data-capability-note]').forEach((note) => { note.textContent = 'Runtime unavailable. No fallback or fabricated result is shown.'; }); document.querySelectorAll('[data-mode]').forEach((button) => { if (button.dataset.mode !== 'ADVISORY') { button.disabled = true; button.classList.add('disabled'); } }); return null; });
    return capabilityPromise;
  }
  function stringify(value) { return typeof value === 'object' ? JSON.stringify(value) : String(value ?? ''); }
  function findObject(value, keys) { if (!value || typeof value !== 'object') return null; for (const key of keys) if (value[key] && typeof value[key] === 'object') return value[key]; for (const child of Object.values(value)) { const found = findObject(child, keys); if (found) return found; } return null; }
  function findText(value, keys) { if (!value || typeof value !== 'object') return null; for (const key of keys) if (typeof value[key] === 'string' || typeof value[key] === 'number') return value[key]; for (const child of Object.values(value)) { const found = findText(child, keys); if (found !== null) return found; } return null; }
  function addDetail(parent, title, entries) { const d = document.createElement('details'); const s = document.createElement('summary'); s.textContent = title; d.append(s); const dl = document.createElement('dl'); entries.filter(([, value]) => value !== undefined && value !== null && value !== '').forEach(([key, value]) => { const dt = document.createElement('dt'); dt.textContent = key; const dd = document.createElement('dd'); dd.textContent = Array.isArray(value) ? value.map(stringify).join(' · ') : stringify(value); dl.append(dt, dd); }); d.append(dl); parent.append(d); }
  function renderTechnical(payload) { const container = $('narrative-details'); if (!container) return; container.replaceChildren(); const result = payload?.result || {}; const workflow = result.workflow || {}; const receipt = result.receipt || workflow.receipt || {}; const thesis = result.thesis || workflow.thesis || {}; const mandate = result.mandate || workflow.mandate || payload.mandate; const council = receipt.council || {}; const evidence = receipt.evidence || {}; addDetail(container, 'Evidence', [['supporting claims', (evidence.supporting || []).map((x) => x.ref)], ['opposing claims', (evidence.opposing || []).map((x) => x.ref)], ['freshness', 'revalidated by the canonical runtime']]); addDetail(container, 'Reasoning Receipt', [['version', receipt.receiptVersion], ['workflow', receipt.workflowId], ['canonical hash', receipt.canonicalSha256], ['rationale', receipt.rationale?.claims?.map((x) => x.statement)]]); addDetail(container, 'Trade Thesis', [['symbol', thesis.symbol], ['direction', thesis.direction], ['expected move', thesis.expectedMove?.bps], ['horizon', thesis.horizonMs], ['invalidation', thesis.invalidation]]); addDetail(container, 'Execution Mandate', [['mandate ID', mandate?.mandateId], ['symbol', mandate?.symbol], ['side', mandate?.side], ['expiry', mandate?.expiresAt], ['uses', mandate?.maxUses], ['entry bounds', mandate?.entry], ['economics', mandate?.economics]]); addDetail(container, 'Runtime receipt', [['workflow status', workflow.status], ['mode', payload.mode], ['no write', payload.noWrite], ['council', council.decision]]); }
  function setTryStage(index) { document.querySelectorAll('.try-stage-bar a').forEach((a, i) => a.classList.toggle('active', i === index)); }
  function renderTryResult(payload) {
    state.payload = payload; state.workflowId = findText(payload, ['workflowId']); const result = payload?.result || {}; const workflow = result.workflow || {}; const receipt = result.receipt || workflow.receipt || {}; const thesis = result.thesis || workflow.thesis || {}; const mandate = result.mandate || workflow.mandate || payload.mandate; const council = receipt.council || {};
    const mode = payload.mode || state.mode; const status = String(payload.status || workflow.status || 'RETURNED'); const refused = /REFUS|COLLAP|DENIED/i.test(status) || /REFUS|COLLAP|DENIED/i.test(String(payload.code || ''));
    $('try-submitted').textContent = `${$('symbol')?.value || 'BTCUSDT'} · ${state.side}`; $('try-submitted-detail').textContent = mode === 'ADVISORY' ? 'Advisory request. No venue execution.' : `${mode} request. No live financial write.`;
    $('try-found').textContent = workflow.status === 'COMPLETE' ? 'Evidence and role analysis returned' : 'Reasoning incomplete'; $('try-found-detail').textContent = 'Advocate, Opposer, and Market Analyst are preserved as the challenge layer.';
    $('try-judgment-value').textContent = council.decision ? `${council.decision} ${council.direction || ''}` : 'No Council decision'; $('try-judgment-detail').textContent = council.confidence !== undefined ? `Confidence ${Math.round(Number(council.confidence) * 100)}%. Strongest opposition: ${council.strongestOpposition || 'not returned'}.` : 'The Council decision is not available.';
    $('try-authority-value').textContent = mandate ? (mode === 'ADVISORY' ? 'MANDATE ISSUED' : 'MANDATE VALID') : 'NO MANDATE'; $('try-authority-detail').textContent = mandate ? `${mandate.symbol || 'BTCUSDT'} · ${mandate.side || 'BUY'} · expires ${mandate.expiresAt || 'bounded expiry'}` : (payload.reason || 'No authority was issued.');
    $('try-outcome-value').textContent = mode === 'ADVISORY' && mandate ? 'MANDATE ISSUED' : refused ? (mandate ? 'EXECUTION REFUSED' : 'NO MANDATE') : status; $('try-outcome-detail').textContent = mode === 'ADVISORY' && mandate ? '0-infinity has finished its job. Keep, verify, or hand off the mandate.' : refused ? (payload.reason || 'The current conditions did not justify action.') : 'The bounded runtime returned this result.';
    setTryStage(refused || mandate ? 4 : 2); renderTechnical(payload); $('receipt-link').disabled = !state.workflowId; $('raw-link').disabled = false; $('verify-link').disabled = !mandate; $('raw-json').textContent = JSON.stringify(payload, null, 2); try { sessionStorage.setItem(TRY_SESSION_KEY, JSON.stringify(payload)); } catch {}
  }
  function compilerPolicy() { return { accountId: 'public-advisory', validityMs: 30000, minExecutableEdgeBps: 1, maxSpreadBps: 20, maxSlippageBps: 1, maxFeeBps: 1, maxFundingCostBps: 1, maxNotional: 100, maxLossBps: 100, execution: 'LIMIT', minEntryPrice: 100000, maxEntryPrice: 100000, entryTrigger: 'BELOW' }; }
  async function callWorkflow(event) { event.preventDefault(); const mode = state.mode; const endpoint = mode === 'ADVISORY' ? '/v1/advisory' : mode === 'PAPER' ? '/v1/paper-live' : '/v1/shadow'; const opportunity = { symbol: $('symbol').value, side: state.side, venue: 'BINANCE', product: 'USD_M_FUTURES' }; const body = mode === 'ADVISORY' ? { opportunity, compilerPolicy: compilerPolicy(), anchor: { stateVersion: `${Date.now()}n`, observedAt: Date.now(), receivedAt: Date.now(), markPrice: 99950 } } : { symbol: opportunity.symbol, side: opportunity.side }; $('run-demo').disabled = true; document.querySelector('.try-result')?.classList.add('is-running'); try { const response = await fetch(`${apiBase}${endpoint}`, { method: 'POST', headers: { 'content-type': 'application/json', accept: 'application/json' }, credentials: 'omit', body: JSON.stringify(body) }); const payload = await response.json(); if (!response.ok) throw new Error(`HTTP ${response.status}`); renderTryResult(payload); } catch (error) { renderTryResult({ mode, status: 'UNAVAILABLE', noWrite: true, workflowId: null, reason: `Runtime unavailable: ${error.message}` }); $('try-outcome-value').textContent = 'NO RESULT'; } finally { $('run-demo').disabled = false; document.querySelector('.try-result')?.classList.remove('is-running'); } }
  function restoreTryResult() { try { const saved = sessionStorage.getItem(TRY_SESSION_KEY); if (saved) renderTryResult(JSON.parse(saved)); } catch { sessionStorage.removeItem(TRY_SESSION_KEY); } }
  function wireTabs(selector, activate) { document.querySelectorAll(selector).forEach((button) => { button.addEventListener('click', () => activate(button.dataset.tab || button.dataset.task)); button.addEventListener('keydown', (event) => { if (!['ArrowRight', 'ArrowDown', 'ArrowLeft', 'ArrowUp'].includes(event.key)) return; const items = [...document.querySelectorAll(selector)]; const index = items.indexOf(button); const next = items[(index + (event.key === 'ArrowRight' || event.key === 'ArrowDown' ? 1 : -1) + items.length) % items.length]; event.preventDefault(); next.focus(); activate(next.dataset.tab || next.dataset.task); }); }); }
  document.addEventListener('DOMContentLoaded', () => { renderRoute(); $('demo-form')?.addEventListener('submit', callWorkflow); document.querySelectorAll('[data-side]').forEach((button) => button.addEventListener('click', () => { state.side = button.dataset.side; document.querySelectorAll('[data-side]').forEach((b) => { b.classList.toggle('selected', b === button); b.setAttribute('aria-pressed', b === button ? 'true' : 'false'); }); })); document.querySelectorAll('[data-mode]').forEach((button) => button.addEventListener('click', () => { state.mode = button.dataset.mode; document.querySelectorAll('[data-mode]').forEach((b) => { b.classList.toggle('selected', b === button); b.setAttribute('aria-pressed', b === button ? 'true' : 'false'); }); $('run-demo').textContent = `Run ${state.mode} →`; })); wireTabs('[data-tab]', renderExample); wireTabs('[data-task]', setTask); $('copy-code')?.addEventListener('click', async () => { try { await navigator.clipboard.writeText($('code-example').textContent); $('copy-code').textContent = 'Copied'; setTimeout(() => { $('copy-code').textContent = 'Copy'; }, 1200); } catch { $('copy-code').textContent = 'Select manually'; } }); $('raw-link')?.addEventListener('click', () => { $('raw-json').hidden = !$('raw-json').hidden; }); $('receipt-link')?.addEventListener('click', () => { const receipt = state.payload?.result?.receipt || state.payload?.result?.workflow?.receipt; if (receipt) $('raw-json').textContent = JSON.stringify(receipt, null, 2); $('raw-json').hidden = false; }); $('verify-link')?.addEventListener('click', () => { $('try-authority-detail').textContent += ' · portable verification is available through 0-infinity/mandate.'; }); });
})();
